{{- if .Values.jupyter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aihub.fullname" (dict "component" "jupyter-secret" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: jupyter
type: Opaque
data:
  # Jupyter token from jupyter service
  JUPYTER_TOKEN: {{ .Values.jupyter.env.JUPYTER_TOKEN | b64enc }}
{{- end }}
