---
name: Pytest Coverage Comment
description: Comments on the PR with the coverage report
inputs:
  working_directory:
    description: Working directory for the pytest coverage report
    required: true
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Sanitize artifact name
      id: sanitize
      shell: bash
      run: echo "artifact_prefix=$(echo '${{ inputs.working_directory }}' | tr '/'
        '-')" >> "$GITHUB_OUTPUT"
    - name: Download pytest reports
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: ${{ steps.sanitize.outputs.artifact_prefix }}-pytest-report
        path: ${{ inputs.working_directory }}
    - name: Download coverage reports
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: ${{ steps.sanitize.outputs.artifact_prefix }}-coverage-report
        path: ${{ inputs.working_directory }}
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@dd5b80bde6d16941f336518e92929e89069d8451  # v1.7.2
      with:
        unique-id-for-comment: ${{ inputs.working_directory }}
        junitxml-path: ${{ inputs.working_directory }}/pytest.xml
        pytest-xml-coverage-path: ${{ inputs.working_directory }}/coverage.xml
        coverage-path-prefix: ${{ inputs.working_directory }}
        title: Coverage Report for ${{ inputs.working_directory }}
        default-branch: main
        report-only-changed-files: true
