---
name: Lint Backend Code
description: Run linter on python backend
inputs:
  github_token:
    description: GitHub token used by reviewdog to post review comments
    required: true
  working_directory:
    description: Working directory for the linter
    required: true
  python_version:
    description: Python version to install
    required: false
    default: '3.13'
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: ${{ inputs.python_version }}
    - name: Set up uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      with:
        enable-cache: true
    - name: Install dependencies
      shell: bash
      run: uv sync --all-packages --dev --frozen
    - name: Install reviewdog
      uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f  # v1.5.0
      with:
        reviewdog_version: v0.21.0
    - name: Lint with Ruff Format
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      run: |-
        uv run ruff format --diff --quiet --check "${{ inputs.working_directory }}" |
          reviewdog -f=diff -f.diff.strip=0 -name=ruff-format -reporter=github-pr-review
