[tool.poetry]
name = "aihub_agent"
version = "v0.91.0"
description = "agents core"
authors = [
    "Joel Barmettler <joel.barmettler@bbv.ch>",
    "Marius Högger <marius.hoegger@bbv.ch>",
    "Michèle Fundneider <michele.fundneider@bbv.ch>",
]
license = "Proprietary"

[tool.poetry.dependencies]
python = ">=3.11, <3.12"
pydantic = "^2.10.3"
nats-py = "^2.9.0"
openinference-instrumentation-llama-index = "^3.0.4"
opentelemetry-sdk = "^1.28.2"
opentelemetry-api = "^1.28.2"
pytest-asyncio = "^0.24.0"
llama-index-core = "^0.12.7"
mongoengine = "^0.29.1"
python-i18n = "^0.3.9"
flatdict = "^4.0.1"
opentelemetry-exporter-otlp = "^1.29.0"
pydantic-settings = "^2.7.0"
colorlog = "^6.9.0"
llama-index-llms-openai = "^0.3.12"
llama-index-llms-azure-openai = "^0.3.0"
pytest-mock = "^3.14.0"
cachetools = "^5.5.2"
redis = "^5.2.1"

[tool.poetry.dependencies.aihub_lib]
git = "https://github.com/bbvch-ai/aihub-core.git"
tag = "v0.91.0"
subdirectory = "aihub_lib"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.24.0"
ruff = "^0.8.1"
isort = "^5.13.2"
mypy = "^1.13.0"
toml-sort = "^0.24.2"
black = { extras = ["jupyter"], version = "^24.10.0" }
pytest-bdd = "^8.1.0"
pytest-cov = "^6.0.0"
tabulate = "^0.9.0"
matplotlib = "^3.10.1"
seaborn = "^0.13.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = 'py311'

[tool.ruff.lint]
extend-ignore = ["E203"]

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
markers = [
    "azure: mark tests that use Azure services",
    "self_hosted: mark tests that use self hosted services",
    "slow: mark a test as slow",
    "integration: mark a test as an integration test",
    "experimental: mark a test as experimental",
]
addopts = "--strict-markers"

