{{- if .Values.dagsterWebserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aihub.fullname" (dict "component" "dagster-config" "Values" .Values "Release" .Release) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster
data:
  dagster.yaml: |
    # Dagster configuration
    storage:
      postgres:
        postgres_db:
          username: "${POSTGRES_USER}"
          password: "${POSTGRES_PASSWORD}"
          hostname: "{{ include "aihub.fullname" (dict "component" "postgres" "Values" .Values "Release" .Release) }}"
          db_name: "dagster"
          port: 5432
{{- end }}
