{{- if .Values.dagsterWebserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aihub.fullname" (dict "component" "dagster-webserver" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster-webserver
spec:
  type: {{ .Values.dagsterWebserver.service.type }}
  ports:
  - port: {{ .Values.dagsterWebserver.service.port }}
    targetPort: 3000
    protocol: TCP
    name: dagster
  selector:
    {{- include "aihub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dagster-webserver
{{- end }}
