{{- if .Values.dagsterWebserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aihub.fullname" (dict "component" "dagster-env" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster
data:
  # Python configuration
  PYTHONUNBUFFERED: "1"
  DAGSTER_HOME: "/dagster_home"
{{- end }}
