{{- if .Values.dagsterWebserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aihub.fullname" (dict "component" "dagster-config" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster
data:
  dagster.yaml: |
    # Dagster configuration
    storage:
      postgres:
        postgres_db:
          username:
            env: POSTGRES_USER
          password:
            env: POSTGRES_PASSWORD
          hostname: "{{ include "aihub.fullname" (dict "component" "postgres" "context" .) }}"
          db_name: "dagster"
          port: 5432
{{- end }}
