{{- if .Values.dagsterWebserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aihub.fullname" (dict "component" "dagster-workspace" "Values" .Values "Release" .Release) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster
data:
  workspace.yaml: |
    # Dagster workspace configuration
    load_from:
      - python_module:
          module_name: "aihub_pipeline"
{{- end }}
