{{- if .Values.milvus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aihub.fullname" (dict "component" "milvus-env" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: milvus
data:
  # Service endpoints
  ETCD_ENDPOINTS: "{{ include "aihub.fullname" (dict "component" "etcd" "context" .) }}:2379"
  MINIO_ADDRESS: "{{ include "aihub.fullname" (dict "component" "minio" "context" .) }}:9000"
{{- end }}
