{{- if .Values.milvus.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aihub.fullname" (dict "component" "milvus-secret" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: milvus
type: Opaque
data:
  # MinIO credentials from minio service
  MINIO_ACCESS_KEY_ID: {{ .Values.minio.env.MINIO_ROOT_USER | b64enc }}
  MINIO_SECRET_ACCESS_KEY: {{ .Values.minio.env.MINIO_ROOT_PASSWORD | b64enc }}
{{- end }}
