[config]
enable_auto_approval = true
auto_approve_for_no_suggestions = true
allow_dynamic_context=true

[pr_reviewer]
enable_review_labels_effort = false

[auto_best_practices]
enable_auto_best_practices = true
utilize_auto_best_practices = true

[pr_code_suggestions]
enable_chat_in_code_suggestions = true
focus_only_on_problems=true
high_level_suggestions_enabled=true
new_diff_format=true

[best_practices]
enable_global_best_practices = true
