
services:
  minio:
    image: ghcr.io/bbvch-ai/aihub-core/minio:release.2024-05-28T17-19-04Z
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  etcd:
    image: ghcr.io/bbvch-ai/aihub-core/etcd:v3.5.16
    container_name: etcd
    restart: always
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/etcd-data:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  milvus-standalone:
    image: ghcr.io/bbvch-ai/aihub-core/milvus:v2.5.15
    container_name: milvus
    restart: always
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/milvus-data:/var/lib/milvus
      - ./configs/milvus/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  attu:
    image: ghcr.io/bbvch-ai/aihub-core/attu:v2.5.12
    container_name: attu
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - "milvus-standalone"
    environment:
     MILVUS_URL: milvus-standalone:19530
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  postgres:
    image: ghcr.io/bbvch-ai/aihub-core/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: openwebui,phoenix,dagster,litellm
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/postgres-data:/var/lib/postgresql/data
      - ./configs/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U webui" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  phoenix:
    image: ghcr.io/bbvch-ai/aihub-core/phoenix:version-10.0.4
    container_name: phoenix
    restart: always
    depends_on:
      - "postgres"
    ports:
      - "6006:6006"
      - "4317:4317"
    environment:
      PHOENIX_SQL_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/phoenix"
      PHOENIX_ENABLE_AUTH: "False"
      VERSION: ""
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  nats:
    image: ghcr.io/bbvch-ai/aihub-core/nats:2.11.4
    container_name: nats
    command: -c /etc/nats/nats.conf
    volumes:
      - ./configs/nats/nats.conf:/etc/nats/nats.conf
      - ${VOLUME_ROOT:-./local-volumes}/nats-data:/data
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    image: ghcr.io/bbvch-ai/aihub-core/redis:8.0.1
    container_name: redis
    command: "redis-server --save 30 1 --loglevel warning"
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/redis-data:/data
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: ghcr.io/bbvch-ai/aihub-core/mongo:8.0.9
    container_name: mongo
    restart: always
    command: >
      --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    logging:
      options:
        max-size: "10m"
        max-file: "2"


  llama-cpp:
    image: ghcr.io/bbvch-ai/aihub-core/llama.cpp:server-b5490
    container_name: llama-cpp
    platform: linux/amd64
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/llama-data:/data
    ports:
      - "8182:8182"
    command: >
      -hf unsloth/Qwen3-0.6B-GGUF
      --port 8182
      --jinja
      -fa 
      -sm row 
      --temp 0.6 
      --top-k 20 
      --top-p 0.95 
      --min-p 0 
      -c 40960 
      -n 32768 
      --no-context-shift
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8182/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  huggingface-text-embedding-inference:
    image: ghcr.io/bbvch-ai/aihub-core/text-embeddings-inference:cpu-1.6
    container_name: huggingface-text-embedding-inference
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/hf-tei-data:/data
    ports:
      - "8183:8183"
    command: >
      --port 8183
      --model-id Alibaba-NLP/gte-base-en-v1.5
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8183/health" ]

  presidio-analyzer:
    image: ghcr.io/bbvch-ai/aihub-core/presidio-analyzer:2.2.359
    container_name: presidio-analyzer
    restart: unless-stopped

  presidio-anonymizer:
    image: ghcr.io/bbvch-ai/aihub-core/presidio-anonymizer:2.2.359
    container_name: presidio-anonymizer
    restart: unless-stopped

  litellm:
    image: ghcr.io/bbvch-ai/aihub-core/litellm:main-v1.74.8-nightly
    container_name: lite-llm
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/litellm"
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      UI_USERNAME: ${LITELLM_UI_USERNAME}
      UI_PASSWORD: ${LITELLM_UI_PASSWORD}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
      AZURE_OPENAI_KEY_IMAGE: ${AZURE_OPENAI_KEY_IMAGE}
      AZURE_OPENAI_KEY_AUDIO: ${AZURE_OPENAI_KEY_AUDIO}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PRESIDIO_ANALYZER_API_BASE: "http://presidio-analyzer:3000"
      PRESIDIO_ANONYMIZER_API_BASE: "http://presidio-anonymizer:3000"
      SET_VERBOSE: "false"
    volumes:
      - ./configs/litellm/litellm.yaml:/app/config.yaml
    command: --config /app/config.yaml --detailed_debug
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      presidio-analyzer:
        condition: service_started
      presidio-anonymizer:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  open-webui:
    image: ghcr.io/bbvch-ai/aihub-core/open-webui:v0.6.13
    network_mode: "host"
    container_name: open-webui
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      litellm:
        condition: service_healthy
      jupyter:
        condition: service_healthy
      playwright:
        condition: service_healthy
      docling:
        condition: service_healthy
    volumes:
      - ./configs/open-webui/config.json:/app/backend/data/config.json
    environment:
      WEBUI_NAME: "Swiss AI-Hub"
      WEBUI_URL: 'localhost:3000'

      ENABLE_FORWARD_USER_INFO_HEADERS: True
      ENABLE_VERSION_UPDATE_CHECK: False

      # Development
      ENV: "dev"                    # dev,test,prod
      GLOBAL_LOG_LEVEL: "DEBUG"     # CRITICAL, FATAL, ERROR, WARN, WARNING, INFO, DEBUG

      # Telemetry
      ENABLE_OTEL: False
      ENABLE_OTEL_METRICS: True
      OTEL_EXPORTER_OTLP_ENDPOINT: XXX
      OTEL_SERVICE_NAME: "open-webui"
      OTEL_BASIC_AUTH_USERNAME: XXX
      OTEL_BASIC_AUTH_PASSWORD: XXX

      # Auth
      WEBUI_AUTH: True
      WEBUI_SESSION_COOKIE_SAME_SITE: "lax"
      WEBUI_SESSION_COOKIE_SECURE: False

      # Oauth
      ENABLE_OAUTH_SIGNUP: True
      OAUTH_PROVIDER_NAME: "azure"
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OPENID_PROVIDER_URL: "${OAUTH_AUTHORITY_URL}/v2.0/.well-known/openid-configuration"
      # OPENID_REDIRECT_URI: XXX

      # Data storage
      STORAGE_PROVIDER: "s3"
      S3_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      S3_REGION_NAME: "us-east-1"
      S3_BUCKET_NAME: "open-webui"
      S3_ENDPOINT_URL: minio:9000

      # Model config
      OPENAI_API_KEY: ${LITELLM_MASTER_KEY}
      OPENAI_API_BASE_URL: "litellm:4000/v1"
      MODELS_CACHE_TTL: 60
      TASK_MODEL: azure/gpt-4o-mini
      TASK_MODEL_EXTERNAL: azure/gpt-4o-mini

      # Database
      DATABASE_TYPE: 'postgres'
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: openwebui

      # Redis
      REDIS_URL: 'redis://redis:6379/1'
      REDIS_KEY_PREFIX: "open-webui"

      # Web server
      UVICORN_WORKERS: 8
      ENABLE_WEBSOCKET_SUPPORT: True
      WEBSOCKET_MANAGER: "redis"
      WEBSOCKET_REDIS_URL: 'redis://redis:6379/1'
      THREAD_POOL_SIZE: 32
      CORS_ALLOW_ORIGIN: "*"

      # Admin
      ENABLE_ADMIN_EXPORT: True
      ENABLE_ADMIN_CHAT_ACCESS: True
      SHOW_ADMIN_DETAILS: true
      ADMIN_EMAIL: admin@ai-hub.bbv.ch

      # Code execution
      CODE_EXECUTION_JUPYTER_URL: http://jupyter:88888
      CODE_EXECUTION_JUPYTER_AUTH: 'token'
      CODE_EXECUTION_JUPYTER_AUTH_TOKEN: ${JUPYTER_TOKEN}

      # Vector DB
      VECTOR_DB: 'milvus'
      MILVUS_DB: 'open-webui'
      MILVUS_URI: milvus-standalone:19530
      MILVUS_INDEX_TYPE: 'HNSW'
      MILVUS_METRIC_TYPE: 'COSINE'
      MILVUS_HNSW_M: '16'
      MILVUS_HNSW_EFCONSTRUCTION: '256'

      # RAG
      CONTENT_EXTRACTION_ENGINE: 'docling'
      DOCLING_SERVER_URL: 'http://docling:5001'

      # Web search
      JINA_API_KEY: ${JINA_API_KEY}
      PLAYWRIGHT_WS_URL: ws://playwright:3000/ws

  jupyter:
    image: ghcr.io/bbvch-ai/aihub-core/minimal-notebook:notebook-7.0.6
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/llama-data:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: yes
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}

  playwright:
    image: ghcr.io/bbvch-ai/aihub-core/playwright:v1.54.1-jammy
    container_name: playwright-server
    command: npx playwright run-server --port 3000 --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  docling:
    image: ghcr.io/bbvch-ai/aihub-core/docling-serve:v1.1.0
    container_name: docling
    ports:
      - "5001:5001"
