services:
  phoenix:
    image: arizephoenix/phoenix:version-7.0.1
    ports:
      - "6006:6006"  # Phoenix UI and OTLP HTTP collector
      - "4317:4317"  # Phoenix OTLP gRPC collector
    depends_on:
      - mongo
      - nats
    restart: always

  nats:
    image: nats:latest
    command: -c /etc/nats/nats.conf
    volumes:
      - ./nats/standalone/nats.conf:/etc/nats/nats.conf
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring interface
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    command: "redis-server --save 30 1 --loglevel warning"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  llama.cpp:
    image: ghcr.io/ggerganov/llama.cpp:server
    platform: linux/amd64
    ports:
      - "8182:8182"
    command: >
      -hf unsloth/Llama-3.2-1B-Instruct-GGUF
      --port 8182
      -c 8192
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8182/health" ]

  hf-TEI:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
    ports:
      - "8183:8183"
    command: >
      --port 8183
      --model-id Alibaba-NLP/gte-base-en-v1.5
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8183/health" ]

volumes:
  redis-data: {}