services:
  phoenix:
    image: ghcr.io/bbvch-ai/aihub-core/phoenix:version-10.0.4
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/phoenix-data:/data
    ports:
      - "6006:6006"
      - "4317:4317"
    restart: always
    healthcheck:
      test: [ "CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:6006/healthz')" ]
      interval: 10s
      timeout: 5s
      retries: 3

  nats:
    image: ghcr.io/bbvch-ai/aihub-core/nats:2.11.4
    command: -c /etc/nats/nats.conf
    volumes:
      - ./nats/standalone/nats.conf:/etc/nats/nats.conf
      - ${VOLUME_ROOT:-./local-volumes}/nats-data:/data
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    image: ghcr.io/bbvch-ai/aihub-core/redis:8.0.1
    container_name: redis
    command: "redis-server --save 30 1 --loglevel warning"
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: ghcr.io/bbvch-ai/aihub-core/mongo:8.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  llama.cpp:
    image: ghcr.io/bbvch-ai/aihub-core/llama.cpp:server-b5490
    platform: linux/amd64
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/llama-data:/data
    ports:
      - "8182:8182"
    command: >
      -hf unsloth/Llama-3.2-1B-Instruct-GGUF
      --port 8182
      -c 8192
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8182/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  hf-TEI:
    image: ghcr.io/bbvch-ai/aihub-core/text-embeddings-inference:cpu-1.6
    volumes:
      - ${VOLUME_ROOT:-./local-volumes}/hf-tei-data:/data
    ports:
      - "8183:8183"
    command: >
      --port 8183
      --model-id Alibaba-NLP/gte-base-en-v1.5
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8183/health" ]