[tool.poetry]
name = "aihub-core"
version = "v0.13.0"
description = "aihub core"
authors = [
    "Thomas Mannhart <thomas.mannhart@bbv.ch>",
]
license = "Proprietary"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11, <3.12"

[tool.poetry.group.dev.dependencies]
tomlkit = "^0.13.2"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
