services:
  aihub-web:
    build: ./aihub_web/aihub_web
    ports:
      - "80:80"
    environment:
      - AZURE_AD_CLIENT_ID=3dc76991-ddd7-4c2d-9cf9-ac2146f33d23
      - AZURE_AD_TENANT_ID=279985bd-2077-4d9d-9797-42238cfc06e2
      - WEBUI_URL=http://localhost:8081
      - WS_ENDPOINT=ws://localhost:8000/api/v1/events/ws