{{- if .Values.defaultRagPipeline.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aihub.fullname" (dict "component" "default-rag-pipeline" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-rag-pipeline
spec:
  serviceName: {{ include "aihub.fullname" (dict "component" "default-rag-pipeline" "context" .) }}
  replicas: {{ .Values.defaultRagPipeline.replicas }}
  selector:
    matchLabels:
      {{- include "aihub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: default-rag-pipeline
  template:
    metadata:
      labels:
        {{- include "aihub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: default-rag-pipeline
    spec:
      {{- include "aihub.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- include "aihub.podSecurityContext" . | nindent 8 }}
      tolerations:
        {{- include "aihub.globalTolerations" . | nindent 8 }}
      containers:
      - name: default-rag-pipeline
        image: {{ .Values.defaultRagPipeline.image.repository }}:{{ .Values.defaultRagPipeline.image.tag }}
        imagePullPolicy: {{ .Values.defaultRagPipeline.image.pullPolicy }}
        securityContext:
          {{- include "aihub.securityContext" . | nindent 10 }}
        env:
        {{- include "aihub.commonEnv" . | nindent 8 }}
        envFrom:
        # Non-sensitive environment variables from Default RAG Pipeline ConfigMap
        - configMapRef:
            name: {{ include "aihub.fullname" (dict "component" "default-rag-pipeline-env" "context" .) }}
        # Sensitive environment variables from Default RAG Pipeline Secret
        - secretRef:
            name: {{ include "aihub.fullname" (dict "component" "default-rag-pipeline-secret" "context" .) }}
        volumeMounts:
        - name: default-rag-pipeline-data
          mountPath: /dagster_home
        resources:
          {{- toYaml .Values.defaultRagPipeline.resources | nindent 10 }}
  volumeClaimTemplates:
  - metadata:
      name: default-rag-pipeline-data
      labels:
        {{- include "aihub.labels" . | nindent 8 }}
        app.kubernetes.io/component: default-rag-pipeline
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.defaultRagPipeline.storage.storageClassName }}
      storageClassName: {{ .Values.defaultRagPipeline.storage.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.defaultRagPipeline.storage.size }}
{{- end }}
