name: SonarCloud Scan
description: Runs the SonarCloud scan on the codebase

inputs:
  sonar_token:
    description: SonarCloud token for authentication
    required: true
  sonar_project_key:
    description: SonarCloud project key
    required: true
  working_directory:
    description: Working directory for the SonarCloud scan
    required: true
  github_token:
    description: GitHub token for authentication
    required: true
  report_coverage:
    description: Report coverage to SonarCloud
    required: false
    default: 'true'
  sonar_organization:
    description: SonarCloud organization
    default: bbv-ai
    required: false

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0
  - name: Download Coverage (if exists)
    uses: actions/download-artifact@v4
    if: inputs.report_coverage == 'true'
    with:
      name: ${{ inputs.working_directory }}-coverage-report
      path: ${{ inputs.working_directory }}
  - name: Run SonarCloud Without Coverage
    if: inputs.report_coverage == 'false'
    uses: SonarSource/sonarqube-scan-action@v5
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
      SONAR_TOKEN: ${{ inputs.sonar_token }}
    with:
      projectBaseDir: ${{ inputs.working_directory }}
      args: >
        -Dsonar.projectKey=${{ inputs.sonar_project_key }}
        -Dsonar.organization=${{ inputs.sonar_organization }}
  - name: Run SonarCloud With Coverage
    if: inputs.report_coverage == 'true'
    uses: SonarSource/sonarqube-scan-action@v5
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
      SONAR_TOKEN: ${{ inputs.sonar_token }}
    with:
      projectBaseDir: ${{ inputs.working_directory }}
      args: >-
        -Dsonar.projectKey=${{ inputs.sonar_project_key }}
        -Dsonar.organization=${{ inputs.sonar_organization }}
        -Dsonar.python.coverage.reportPaths=${{ inputs.working_directory }}/coverage.xml
