#!/bin/bash
# Helper script to add a new agent development container
#
# Usage:
#   ./deployment/agent-dev/add-agent.sh <agent-name> <agent-number>
#
# Example:
#   ./deployment/agent-dev/add-agent.sh legal 2
#
# This creates:
#   - Service: agent-2-dev (legal agent)
#   - VS Code port: 8444
#   - OpenCode port: 8081
#   - Code path: ./agents/legal/

set -e

# Check arguments
if [ $# -ne 2 ]; then
    echo "Usage: $0 <agent-name> <agent-number>"
    echo ""
    echo "Examples:"
    echo "  $0 legal 2       # Creates agent-2-dev for legal agent"
    echo "  $0 product 3     # Creates agent-3-dev for product agent"
    echo "  $0 support 4     # Creates agent-4-dev for support agent"
    exit 1
fi

AGENT_NAME=$1
AGENT_NUMBER=$2
SERVICE_NAME="agent-${AGENT_NUMBER}-dev"
VSCODE_PORT=$((8442 + AGENT_NUMBER))  # 8443, 8444, 8445, ...
OPENCODE_PORT=$((8079 + AGENT_NUMBER)) # 8080, 8081, 8082, ...
CODE_PATH="./agents/${AGENT_NAME}"

echo "================================================"
echo "Adding Agent Development Container"
echo "================================================"
echo ""
echo "Configuration:"
echo "  Agent Name:      ${AGENT_NAME}"
echo "  Agent Number:    ${AGENT_NUMBER}"
echo "  Service Name:    ${SERVICE_NAME}"
echo "  VS Code Port:    ${VSCODE_PORT}"
echo "  OpenCode Port:   ${OPENCODE_PORT}"
echo "  Code Path:       ${CODE_PATH}"
echo ""

# Check if service already exists
if grep -q "${SERVICE_NAME}:" docker-compose.agent-dev.yml; then
    echo "❌ Error: Service '${SERVICE_NAME}' already exists in docker-compose.agent-dev.yml"
    exit 1
fi

# Create code directory
echo "📁 Creating code directory: ${CODE_PATH}"
mkdir -p "${CODE_PATH}"

# Create basic README in agent directory
cat > "${CODE_PATH}/README.md" << EOF
# ${AGENT_NAME^} Agent

Development container for ${AGENT_NAME} agent.

## Access

- **VS Code:** http://localhost:${VSCODE_PORT}
- **OpenCode:** Internal port ${OPENCODE_PORT}

## Quick Start

1. Open VS Code: http://localhost:${VSCODE_PORT}
2. Enter password (from .env.agent-dev)
3. Open terminal
4. Run: \`opencode client --server localhost:8080\`
5. Tell OpenCode what to build!

## Development

\`\`\`bash
# In VS Code terminal

# Install dependencies
poetry install

# Run tests
pytest tests/ -v

# Run agent
python -m trigger
\`\`\`

## Traces

View in Phoenix: http://localhost:6006
EOF

echo "✅ Created ${CODE_PATH}/README.md"

# Generate service definition
SERVICE_DEF=$(cat << EOF

  # ===================================================================
  # Agent ${AGENT_NUMBER}: ${AGENT_NAME^} Agent
  # Generated by: add-agent.sh ${AGENT_NAME} ${AGENT_NUMBER}
  # ===================================================================
  ${SERVICE_NAME}:
    container_name: ${SERVICE_NAME}
    build:
      context: ./deployment/agent-dev
      dockerfile: Dockerfile.agent-dev
      args:
        USERNAME: developer
        USER_UID: 1000
        USER_GID: 1000
    stdin_open: true
    tty: true
    ports:
      - "${VSCODE_PORT}:8443"  # VS Code
      - "${OPENCODE_PORT}:8080"  # OpenCode
    volumes:
      # Agent source code (persists on host)
      - ${CODE_PATH}:/workspace/agent:rw

      # Shared libraries (read-only)
      - ./aihub_lib:/workspace/aihub_lib:ro
      - ./aihub_agent/aihub_agent:/workspace/aihub_agent:ro

      # Documentation for AI context
      - ./AGENTS.md:/workspace/AGENTS.md:ro
      - ./AI_AGENT_BUILD_AND_DEPLOY_GUIDE.md:/workspace/BUILD_GUIDE.md:ro
      - ./aihub_agent/AGENTS.md:/workspace/aihub_agent_guide.md:ro

      # Poetry files for dependency management
      - ./aihub_agent/pyproject.toml:/workspace/pyproject.toml:ro
      - ./aihub_agent/poetry.lock:/workspace/poetry.lock:ro

      # Persist VS Code settings and extensions
      - agent-${AGENT_NUMBER}-vscode-data:/home/developer/.local/share/code-server

      # Persist bash history
      - agent-${AGENT_NUMBER}-bash-history:/home/developer/.bash_history_mount
    environment:
      # Infrastructure endpoints
      NATS_URL: nats://nats:4222
      REDIS_URL: redis://redis:6379
      POSTGRES_URL: postgresql://admin:admin@postgres:5432/aihub
      MILVUS_HOST: milvus
      MILVUS_PORT: 19530
      PHOENIX_COLLECTOR_ENDPOINT: http://phoenix:6006

      # Development settings
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: DEBUG
      ENVIRONMENT: development

      # VS Code password
      PASSWORD: \${AGENT_${AGENT_NUMBER}_PASSWORD:-developer}

      # Agent identification
      AGENT_NAME: ${AGENT_NAME}

      # Port info (for display in logs)
      VSCODE_PORT: ${VSCODE_PORT}
      OPENCODE_PORT: ${OPENCODE_PORT}

      # Preserve bash history
      HISTFILE: /home/developer/.bash_history_mount/.bash_history
    depends_on:
      nats:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      milvus:
        condition: service_healthy
      phoenix:
        condition: service_healthy
    networks:
      - agent-dev-network
EOF
)

# Add service to docker-compose.yml (before the networks section)
echo ""
echo "📝 Adding service to docker-compose.agent-dev.yml..."

# Use awk to insert before the networks section
awk -v service="$SERVICE_DEF" '
/^networks:/ && !done {
    print service
    done=1
}
{print}
' docker-compose.agent-dev.yml > docker-compose.agent-dev.yml.tmp

mv docker-compose.agent-dev.yml.tmp docker-compose.agent-dev.yml

# Add volumes
echo "📝 Adding volumes..."

# Append volumes at the end
cat >> docker-compose.agent-dev.yml << EOF
  agent-${AGENT_NUMBER}-vscode-data:
  agent-${AGENT_NUMBER}-bash-history:
EOF

echo "✅ Updated docker-compose.agent-dev.yml"

# Add to .env template if exists
if [ -f ".env.agent-dev.template" ]; then
    echo ""
    echo "📝 Adding password to .env.agent-dev.template..."

    if ! grep -q "AGENT_${AGENT_NUMBER}_PASSWORD" .env.agent-dev.template; then
        cat >> .env.agent-dev.template << EOF

# Agent ${AGENT_NUMBER} - ${AGENT_NAME^} agent
AGENT_${AGENT_NUMBER}_PASSWORD=secure-password-${AGENT_NAME}-${AGENT_NUMBER}
EOF
        echo "✅ Updated .env.agent-dev.template"
    else
        echo "⚠️  Password already exists in .env.agent-dev.template"
    fi
fi

# Update .env.agent-dev if exists
if [ -f ".env.agent-dev" ]; then
    if ! grep -q "AGENT_${AGENT_NUMBER}_PASSWORD" .env.agent-dev; then
        echo ""
        echo "📝 Adding password to .env.agent-dev..."
        cat >> .env.agent-dev << EOF

# Agent ${AGENT_NUMBER} - ${AGENT_NAME^} agent
AGENT_${AGENT_NUMBER}_PASSWORD=developer
EOF
        echo "✅ Updated .env.agent-dev"
    fi
fi

echo ""
echo "================================================"
echo "✅ Agent ${AGENT_NUMBER} (${AGENT_NAME}) Added Successfully!"
echo "================================================"
echo ""
echo "Next Steps:"
echo ""
echo "1. Review the configuration in docker-compose.agent-dev.yml"
echo ""
echo "2. Set password in .env.agent-dev:"
echo "   AGENT_${AGENT_NUMBER}_PASSWORD=your-secure-password"
echo ""
echo "3. Start the container:"
echo "   docker-compose -f docker-compose.agent-dev.yml up -d ${SERVICE_NAME}"
echo ""
echo "4. Access VS Code:"
echo "   http://localhost:${VSCODE_PORT}"
echo ""
echo "5. Start building!"
echo "   - Open terminal in VS Code"
echo "   - Run: opencode client --server localhost:8080"
echo "   - Tell OpenCode what to build"
echo ""
echo "Code Location: ${CODE_PATH}"
echo "================================================"
