import json
from typing import Annotated, Any, Dict, Optional, Union

from aihub_lib.i18n.LocaleHandler import LocaleHandler
from aihub_lib.nats.events import (
    AgentEvent,
    AgentInTheLoopExceptionEvent,
    AgentInTheLoopRequestEvent,
    AgentInTheLoopResponseEvent,
    ChainEvent,
    ChunkEvent,
    DisplayEvent,
    EmbeddingEvent,
    ExceptionEvent,
    GuardRejectionEvent,
    HumanInTheLoopRequestEvent,
    HumanInTheLoopResponseEvent,
    LimitChatHistoryEvent,
    LLMCostEvent,
    LLMEvent,
    LLMStopEvent,
    RerankerEvent,
    RetrieverEvent,
    StandaloneQuestionCondenserEvent,
    StartEvent,
    StopEvent,
    ThoughtEvent,
    ToolEvent,
    UserMessageEvent,
)
from aihub_lib.nats.events.router.RouterEvent import RouterEvent
from aihub_lib.nats.events.semantic import SemanticEvent
from aihub_lib.nats.events.semantic.guard import GuardEvent
from aihub_lib.nats.topic_managers.agents.AgentTopicManager import AgentTopicManager
from aihub_lib.persistence.messaging.entities.PersistedEventEntity import PersistedEventEntity
from pydantic import BaseModel, Discriminator, Field, Tag
from typing_extensions import override

# Import all events here that the frontend should be able to display
DisplayEvents = Union[
    Annotated[StartEvent, Tag("StartEvent")],
    Annotated[AgentInTheLoopResponseEvent, Tag("AgentInTheLoopResponseEvent")],
    Annotated[HumanInTheLoopRequestEvent, Tag("HumanInTheLoopRequestEvent")],
    Annotated[AgentInTheLoopRequestEvent, Tag("AgentInTheLoopRequestEvent")],
    Annotated[AgentInTheLoopExceptionEvent, Tag("AgentInTheLoopExceptionEvent")],
    Annotated[HumanInTheLoopResponseEvent, Tag("HumanInTheLoopResponseEvent")],
    Annotated[LimitChatHistoryEvent, Tag("LimitChatHistoryEvent")],
    Annotated[StandaloneQuestionCondenserEvent, Tag("StandaloneQuestionCondenserEvent")],
    Annotated[LLMCostEvent, Tag("LLMCostEvent")],
    Annotated[ChunkEvent, Tag("ChunkEvent")],
    Annotated[ThoughtEvent, Tag("ThoughtEvent")],
    Annotated[GuardEvent, Tag("GuardEvent")],
    Annotated[RouterEvent, Tag("RouterEvent")],
    Annotated[GuardRejectionEvent, Tag("GuardRejectionEvent")],
    Annotated[SemanticEvent, Tag("SemanticEvent")],
    Annotated[AgentEvent, Tag("AgentEvent")],
    Annotated[ChainEvent, Tag("ChainEvent")],
    Annotated[EmbeddingEvent, Tag("EmbeddingEvent")],
    Annotated[LLMEvent, Tag("LLMEvent")],
    Annotated[LLMStopEvent, Tag("LLMStopEvent")],
    Annotated[RerankerEvent, Tag("RerankerEvent")],
    Annotated[RetrieverEvent, Tag("RetrieverEvent")],
    Annotated[ToolEvent, Tag("ToolEvent")],
    Annotated[StartEvent, Tag("StartEvent")],
    Annotated[UserMessageEvent, Tag("UserMessageEvent")],
    Annotated[ExceptionEvent, Tag("ExceptionEvent")],
    Annotated[StopEvent, Tag("StopEvent")],
    Annotated[DisplayEvent, Tag("DisplayEvent")],
]


def event_discriminator(event: DisplayEvent) -> str:
    # Get all tags from DisplayEvents union
    valid_tags = [arg.__metadata__[0].tag for arg in DisplayEvents.__args__]

    # Return "DisplayEvent" if _event_name is missing or not in valid_tags
    if not hasattr(event, "_event_name"):
        return "DisplayEvent"

    if event._event_name in valid_tags:
        return event._event_name

    for event_name in event._parent_event_names:
        if event_name in valid_tags:
            return event_name

    return "DisplayEvent"


class WSServerEvent(BaseModel):
    """
    Represents an event sent from the server to a user's WebSocket connection, encapsulating
    details necessary to identify and display the event in a client application.

    ### Why WSServerEvent?
    In a real-time system, events generated by agents need to be transmitted to clients over
    WebSockets. A `WSServerEvent` standardizes the structure of these messages, including:
    - Agent identifiers and context (thread/display/run).
    - Event type, name, and ID for classification.
    - Payload (`event_data`) containing the actual event content.

    This consistency helps front-end clients parse and handle events uniformly, and aids in
    debugging or logging outbound messages.

    ### Conversion from Persisted Events
    The `from_persisted_event` method rebuilds a `WSServerEvent` from a `PersistedEventEntity`,
    allowing previously stored events to be replayed or displayed to users.
    """

    locale: str = Field(
        LocaleHandler.DEFAULT_LOCALE,
        description="The locale in which event name and description is returned.",
    )
    event_display_name: Annotated[str, Field(None, description="Display name for the event")]
    event_display_description: Annotated[str, Field(None, description="Display description for the event")]

    agent_class: str = Field(..., description="The agent class responsible for this event.")
    agent_id: str = Field(..., description="Unique identifier of the agent instance that produced the event.")
    thread_id: str = Field(
        ..., description="Thread identifier linking events to a particular conversation or workflow."
    )
    display_id: str = Field(..., description="Display session ID, used to group events for the UI.")
    run_id: Optional[str] = Field(None, description="Optional run ID if the event is associated with a particular run.")
    event_type: Optional[str] = Field(
        AgentTopicManager.DISPLAY_EVENT, description="Type of the event (default: 'display_event')."
    )
    event_name: str = Field(..., description="Name of the event, indicating its subtype or category.")
    event_id: str = Field(..., description="Unique identifier of this event instance.")
    event: DisplayEvents = Field(
        ...,
        description="Data of the event itself.",
        discriminator=Discriminator(event_discriminator),
    )

    @classmethod
    def from_persisted_event(
        cls, persisted_event: PersistedEventEntity, locale: Optional[str] = None
    ) -> "WSServerEvent":
        """
        Construct a WSServerEvent from a PersistedEventEntity, converting persisted event data
        into a client-ready format.
        """
        locale_handler = LocaleHandler(locale=locale)
        display_event = DisplayEvent.deserialize_event(persisted_event.event_data)
        return cls(
            locale=locale or locale_handler.DEFAULT_LOCALE,
            agent_class=persisted_event.agent_class,
            agent_id=persisted_event.agent_id,
            thread_id=persisted_event.thread_id,
            display_id=persisted_event.display_id,
            run_id=persisted_event.run_id,
            event_type=persisted_event.event_type,
            event_name=persisted_event.event_name,
            event_id=persisted_event.event_id,
            event=display_event,
            event_display_name=locale_handler.extract(display_event.display_name),
            event_display_description=locale_handler.extract(display_event.display_description),
        )

    @override
    def model_dump(self, **kwargs: Any) -> Dict[str, Any]:
        """
        Serializes the event into a dictionary. If this event was originally unknown,
        merges the original data with the known fields so nothing is lost.
        """
        data = super().model_dump(**kwargs)
        return {**data, "event": self.event.model_dump(**kwargs)}

    @override
    def model_dump_json(self, **kwargs: Any) -> str:
        """
        Serializes the event into a JSON string. If this event was originally unknown,
        merges the original data with the known fields so nothing is lost.
        """
        return json.dumps(self.model_dump(**kwargs), default=str)
