{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aihub.fullname" (dict "component" "mongo" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  serviceName: {{ include "aihub.fullname" (dict "component" "mongo" "context" .) }}
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      {{- include "aihub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongo
  template:
    metadata:
      labels:
        {{- include "aihub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongo
    spec:
      {{- include "aihub.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- include "aihub.podSecurityContext" . | nindent 8 }}
      tolerations:
        {{- include "aihub.globalTolerations" . | nindent 8 }}
      containers:
      - name: mongo
        image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        securityContext:
          {{- include "aihub.securityContext" . | nindent 10 }}
        command:
        - mongod
        - --quiet
        - --bind_ip_all
        env:
        {{- include "aihub.commonEnv" . | nindent 8 }}
        envFrom:
        # Sensitive environment variables from Mongo Secret
        - secretRef:
            name: {{ include "aihub.fullname" (dict "component" "mongo-secret" "context" .) }}
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          {{- toYaml .Values.mongo.resources | nindent 10 }}
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
{{- end }}
