{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aihub.fullname" (dict "component" "minio-secret" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
data:
  # MinIO credentials from minio service
  MINIO_ROOT_USER: {{ .Values.minio.env.MINIO_ROOT_USER | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.env.MINIO_ROOT_PASSWORD | b64enc }}
{{- end }}
