{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aihub.fullname" (dict "component" "minio" "Values" .Values "Release" .Release) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
  - port: {{ .Values.minio.service.port }}
    targetPort: 9000
    protocol: TCP
    name: api
  - port: {{ .Values.minio.service.consolePort }}
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    {{- include "aihub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }}
