sonar.projectKey=swiss-ai-hub_agent
sonar.organization=bbv-ai
# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Swiss AI Hub Agent
sonar.projectVersion=1.0
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=swiss_ai_hub
sonar.tests=swiss_ai_hub
sonar.test.inclusions=**/test_*.py
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8