// This file is auto-generated by @hey-api/openapi-ts

import type { ListTokensEndpointResponse, CreateTokenEndpointResponse } from './types.gen'

const tokenResponseSchemaResponseTransformer = (data: any) => {
  data.expiry_date = new Date(data.expiry_date)
  return data
}

export const listTokensEndpointResponseTransformer = async (data: any): Promise<ListTokensEndpointResponse> => {
  data = data.map((item: any) => {
    return tokenResponseSchemaResponseTransformer(item)
  })
  return data
}

const createTokenResponseSchemaResponseTransformer = (data: any) => {
  data.expiry_date = new Date(data.expiry_date)
  return data
}

export const createTokenEndpointResponseTransformer = async (data: any): Promise<CreateTokenEndpointResponse> => {
  data = createTokenResponseSchemaResponseTransformer(data)
  return data
}
