// This file is auto-generated by @hey-api/openapi-ts

import type { GetMyAccountResponse, GetUsersResponse, GetUserResponse, GetAgentEventTimeseriesResponse, ListTokensEndpointResponse, CreateTokenEndpointResponse, GetDatasetsResponse, CreateDatasetResponse, GetDatasetResponse, UpdateDatasetResponse, GetExperimentResponse, GetExperimentsResponse, RunExperimentResponse, GetNotificationsResponse, UpdateNotificationsBulkResponse, UpdateNotificationResponse } from './types.gen';

const userWithAccessDtoSchemaResponseTransformer = (data: any) => {
    data.last_accessed = new Date(data.last_accessed);
    return data;
};

export const getMyAccountResponseTransformer = async (data: any): Promise<GetMyAccountResponse> => {
    data = userWithAccessDtoSchemaResponseTransformer(data);
    return data;
};

const userDtoSchemaResponseTransformer = (data: any) => {
    data.last_accessed = new Date(data.last_accessed);
    return data;
};

const paginatedUsersResponseSchemaResponseTransformer = (data: any) => {
    data.users = data.users.map((item: any) => {
        return userDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const getUsersResponseTransformer = async (data: any): Promise<GetUsersResponse> => {
    data = paginatedUsersResponseSchemaResponseTransformer(data);
    return data;
};

export const getUserResponseTransformer = async (data: any): Promise<GetUserResponse> => {
    data = userWithAccessDtoSchemaResponseTransformer(data);
    return data;
};

const eventBucketSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

const eventTimeseriesSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    data.buckets = data.buckets.map((item: any) => {
        return eventBucketSchemaResponseTransformer(item);
    });
    return data;
};

export const getAgentEventTimeseriesResponseTransformer = async (data: any): Promise<GetAgentEventTimeseriesResponse> => {
    data = eventTimeseriesSchemaResponseTransformer(data);
    return data;
};

const tokenResponseSchemaResponseTransformer = (data: any) => {
    data.expiry_date = new Date(data.expiry_date);
    return data;
};

export const listTokensEndpointResponseTransformer = async (data: any): Promise<ListTokensEndpointResponse> => {
    data = data.map((item: any) => {
        return tokenResponseSchemaResponseTransformer(item);
    });
    return data;
};

const createTokenResponseSchemaResponseTransformer = (data: any) => {
    data.expiry_date = new Date(data.expiry_date);
    return data;
};

export const createTokenEndpointResponseTransformer = async (data: any): Promise<CreateTokenEndpointResponse> => {
    data = createTokenResponseSchemaResponseTransformer(data);
    return data;
};

const minimalDatasetSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

export const getDatasetsResponseTransformer = async (data: any): Promise<GetDatasetsResponse> => {
    data = data.map((item: any) => {
        return minimalDatasetSchemaResponseTransformer(item);
    });
    return data;
};

const datasetSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

export const createDatasetResponseTransformer = async (data: any): Promise<CreateDatasetResponse> => {
    data = datasetSchemaResponseTransformer(data);
    return data;
};

export const getDatasetResponseTransformer = async (data: any): Promise<GetDatasetResponse> => {
    data = datasetSchemaResponseTransformer(data);
    return data;
};

export const updateDatasetResponseTransformer = async (data: any): Promise<UpdateDatasetResponse> => {
    data = datasetSchemaResponseTransformer(data);
    return data;
};

const experimentRunRecordSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

const experimentSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    data.dataset = minimalDatasetSchemaResponseTransformer(data.dataset);
    data.items = data.items.map((item: any) => {
        return experimentRunRecordSchemaResponseTransformer(item);
    });
    return data;
};

export const getExperimentResponseTransformer = async (data: any): Promise<GetExperimentResponse> => {
    data = experimentSchemaResponseTransformer(data);
    return data;
};

const minimalExperimentSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    data.dataset = minimalDatasetSchemaResponseTransformer(data.dataset);
    return data;
};

export const getExperimentsResponseTransformer = async (data: any): Promise<GetExperimentsResponse> => {
    data = data.map((item: any) => {
        return minimalExperimentSchemaResponseTransformer(item);
    });
    return data;
};

export const runExperimentResponseTransformer = async (data: any): Promise<RunExperimentResponse> => {
    data = experimentSchemaResponseTransformer(data);
    return data;
};

const notificationDtoSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

const paginatedNotificationsResponseSchemaResponseTransformer = (data: any) => {
    data.notifications = data.notifications.map((item: any) => {
        return notificationDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const getNotificationsResponseTransformer = async (data: any): Promise<GetNotificationsResponse> => {
    data = paginatedNotificationsResponseSchemaResponseTransformer(data);
    return data;
};

export const updateNotificationsBulkResponseTransformer = async (data: any): Promise<UpdateNotificationsBulkResponse> => {
    data = data.map((item: any) => {
        return notificationDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const updateNotificationResponseTransformer = async (data: any): Promise<UpdateNotificationResponse> => {
    data = notificationDtoSchemaResponseTransformer(data);
    return data;
};