// This file is auto-generated by @hey-api/openapi-ts

import type { GetThreadTimeStatisticsResponse, ListTokensEndpointResponse, CreateTokenEndpointResponse } from './types.gen';

const eventBucketSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

const threadTimeStatisticsDtoSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    data.buckets = data.buckets.map((item: any) => {
        return eventBucketSchemaResponseTransformer(item);
    });
    return data;
};

export const getThreadTimeStatisticsResponseTransformer = async (data: any): Promise<GetThreadTimeStatisticsResponse> => {
    data = threadTimeStatisticsDtoSchemaResponseTransformer(data);
    return data;
};

const tokenResponseSchemaResponseTransformer = (data: any) => {
    data.expiry_date = new Date(data.expiry_date);
    return data;
};

export const listTokensEndpointResponseTransformer = async (data: any): Promise<ListTokensEndpointResponse> => {
    data = data.map((item: any) => {
        return tokenResponseSchemaResponseTransformer(item);
    });
    return data;
};

const createTokenResponseSchemaResponseTransformer = (data: any) => {
    data.expiry_date = new Date(data.expiry_date);
    return data;
};

export const createTokenEndpointResponseTransformer = async (data: any): Promise<CreateTokenEndpointResponse> => {
    data = createTokenResponseSchemaResponseTransformer(data);
    return data;
};