// This file is auto-generated by @hey-api/openapi-ts

export type AddAgentRequest = {
  agent_id: string;
  agent_class: string;
};

export type AddUserRequest = {
  user_id: string;
};

export type AgentConfigDto = {
  /**
   * The id of the agent.
   */
  agent_id: string;
  /**
   * The name of the agent.
   */
  name: string;
  /**
   * The description of the agent.
   */
  description: string;
  /**
   * The system prompt of the agent.
   */
  system_prompt: string;
  /**
   * The color of the agent UI theme.
   */
  color?: string;
  /**
   * The TTS voice ID the agent uses.
   */
  voice?: string;
  /**
   * The icon representing the agent.
   */
  icon?: string;
};

/**
 * A data transfer object for representing agent information in responses.
 *
 * ### Why AgentDTO?
 * This DTO standardizes how agent data is returned from the service layer to the controller,
 * and subsequently to the API response. It helps maintain a clean separation between the internal
 * event models and the publicly exposed fields in HTTP responses.
 *
 * By using `AgentDTO`, the API can evolve independently from the internal event representations.
 */
export type AgentDto = {
  /**
   * The agent's class identifier (e.g., 'my_agent_class').
   */
  agent_class: string;
  /**
   * Unique identifier for the agent instance (e.g., 'agent_123').
   */
  agent_id: string;
  /**
   * Configuration details of the agent, including name, description, and prompts.
   */
  agent_config: AgentConfigDto;
  /**
   * Whether the agent can participate in a chat-based conversation
   */
  is_conversational: boolean;
  /**
   * A list of `EventSpecs` representing events that can start this agent's workflow.
   */
  start_events: Array<EventSpecs>;
  /**
   * A list of `EventSpecs` representing events that can stop this agent's workflow.
   */
  stop_events: Array<EventSpecs>;
};

export type BodyCreateTranscriptionOpenaiAudioTranscriptionsPost = {
  /**
   * The audio file to transcribe
   */
  file: Blob | File;
  /**
   * ID of the model to use
   */
  model: string;
  /**
   * ISO-639-1 language code
   */
  language?: string | null;
  /**
   * Optional text prompt
   */
  prompt?: string | null;
  /**
   * Format of the response
   */
  response_format?: string | null;
  /**
   * Sampling temperature between 0 and 1
   */
  temperature?: number | null;
  /**
   * Timestamp granularities (e.g. 'word' or 'segment'); only used with verbose_json response_format
   */
  timestamp_granularities?: Array<"word" | "segment"> | null;
};

export type ChatCompletion = {
  id: string;
  choices: Array<Choice>;
  created: number;
  model: string;
  object: "chat.completion";
  service_tier?: ("scale" | "default") | null;
  system_fingerprint?: string | null;
  usage?: CompletionUsage | null;
  [key: string]:
    | unknown
    | string
    | Array<Choice>
    | number
    | "chat.completion"
    | (("scale" | "default") | null)
    | (string | null)
    | (CompletionUsage | null)
    | undefined;
};

export type ChatCompletionAudio = {
  id: string;
  data: string;
  expires_at: number;
  transcript: string;
  [key: string]: unknown | string | number;
};

export type ChatCompletionMessage = {
  content?: string | null;
  refusal?: string | null;
  role: "assistant";
  audio?: ChatCompletionAudio | null;
  function_call?: FunctionCall | null;
  tool_calls?: Array<ChatCompletionMessageToolCall> | null;
  [key: string]:
    | unknown
    | (string | null)
    | (string | null)
    | "assistant"
    | (ChatCompletionAudio | null)
    | (FunctionCall | null)
    | (Array<ChatCompletionMessageToolCall> | null)
    | undefined;
};

export type ChatCompletionMessageToolCall = {
  id: string;
  function: _Function;
  type: "function";
  [key: string]: unknown | string | _Function | "function";
};

export type ChatCompletionRequest = {
  /**
   * ID of the model to use for the chat completion.
   */
  model: string;
  /**
   * Enable streaming response.
   */
  stream?: boolean;
  [key: string]: unknown | string | boolean | undefined;
};

export type ChatCompletionTokenLogprob = {
  token: string;
  bytes?: Array<number> | null;
  logprob: number;
  top_logprobs: Array<TopLogprob>;
  [key: string]:
    | unknown
    | string
    | (Array<number> | null)
    | number
    | Array<TopLogprob>
    | undefined;
};

export type Choice = {
  finish_reason:
    | "stop"
    | "length"
    | "tool_calls"
    | "content_filter"
    | "function_call";
  index: number;
  logprobs?: ChoiceLogprobs | null;
  message: ChatCompletionMessage;
  [key: string]:
    | unknown
    | ("stop" | "length" | "tool_calls" | "content_filter" | "function_call")
    | number
    | (ChoiceLogprobs | null)
    | ChatCompletionMessage
    | undefined;
};

export type ChoiceLogprobs = {
  content?: Array<ChatCompletionTokenLogprob> | null;
  refusal?: Array<ChatCompletionTokenLogprob> | null;
  [key: string]:
    | unknown
    | (Array<ChatCompletionTokenLogprob> | null)
    | (Array<ChatCompletionTokenLogprob> | null)
    | undefined;
};

export type CompletionTokensDetails = {
  accepted_prediction_tokens?: number | null;
  audio_tokens?: number | null;
  reasoning_tokens?: number | null;
  rejected_prediction_tokens?: number | null;
  [key: string]:
    | unknown
    | (number | null)
    | (number | null)
    | (number | null)
    | (number | null)
    | undefined;
};

export type CompletionUsage = {
  completion_tokens: number;
  prompt_tokens: number;
  total_tokens: number;
  completion_tokens_details?: CompletionTokensDetails | null;
  prompt_tokens_details?: PromptTokensDetails | null;
  [key: string]:
    | unknown
    | number
    | (CompletionTokensDetails | null)
    | (PromptTokensDetails | null)
    | undefined;
};

export type CreateThreadRequest = {
  name: string;
  user_ids?: Array<string>;
  agents?: Array<ThreadAgentDto>;
};

export type CreateTokenRequest = {
  /**
   * Token name between 1 and 100 characters
   */
  name: string;
  /**
   * Expiry date in ISO format (must be in the future)
   */
  expiry_date: Date;
  /**
   * Non-empty list of roles associated with the token
   */
  roles: Array<string>;
};

export type CreateTokenResponse = {
  /**
   * The token ID
   */
  id: string;
  name: string;
  /**
   * Expiry date
   */
  expiry_date: Date;
  /**
   * List of roles granted to the access token
   */
  roles: Array<string>;
  /**
   * The generated API token, only returned at creation
   */
  token: string;
};

export type Embeddings = {
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The list of embeddings.
   */
  embedding: Array<number>;
  /**
   * The index of the embedding.
   */
  index: number;
};

export type EmbeddingsRequest = {
  /**
   * Input text to embed. Can be a string, array of strings, or arrays of tokens. Must not exceed max input tokens.
   */
  input: string | Array<string> | Array<number> | Array<Array<number>>;
  /**
   * ID of the model to use for generating embeddings.
   */
  model: string;
  /**
   * Format of the returned embeddings. Defaults to 'float'.
   */
  encoding_format?: ("float" | "base64") | null;
  /**
   * Number of dimensions for output embeddings. Supported in text-embedding-3 and later models.
   */
  dimensions?: number | null;
  /**
   * A unique identifier for the end-user to monitor and detect abuse.
   */
  user?: string | null;
};

export type EmbeddingsResponse = {
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The model name.
   */
  model: string;
  /**
   * The list of embeddings.
   */
  data: Array<Embeddings>;
};

/**
 * Defines a specification for a start event that an agent can handle.
 */
export type EventSpecs = {
  /**
   * The type of event (e.g., a particular ControlEvent subclass name) that the agent can consume as a start event.
   */
  event_type: string;
  /**
   * A dictionary describing the schema of this start event, providing details about expected fields and their types. This helps external consumers understand how to construct and validate events for initiating the agent's workflow.
   */
  event_schema: {
    [key: string]: unknown;
  };
};

export type _Function = {
  arguments: string;
  name: string;
  [key: string]: unknown | string;
};

export type FunctionCall = {
  arguments: string;
  name: string;
  [key: string]: unknown | string;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

export type HealthResponse = {
  /**
   * The health status of the application.
   */
  status: string;
};

export type Image = {
  b64_json?: string | null;
  revised_prompt?: string | null;
  url?: string | null;
  [key: string]:
    | unknown
    | (string | null)
    | (string | null)
    | (string | null)
    | undefined;
};

export type ImageGenerationRequest = {
  /**
   * A text description of the desired image(s). Max 1000 characters for DALL-E 2, 4000 for DALL-E 3.
   */
  prompt: string;
  /**
   * The model to use for image generation. Defaults to dall-e-2.
   */
  model?: ("dall-e-2" | "dall-e-3") | null;
  [key: string]:
    | unknown
    | string
    | (("dall-e-2" | "dall-e-3") | null)
    | undefined;
};

export type ImagesResponse = {
  created: number;
  data: Array<Image>;
  [key: string]: unknown | number | Array<Image>;
};

/**
 * Represents language and test information for a locale.
 */
export type LocaleResponse = {
  /**
   * The language code for the locale
   */
  lang: string;
  /**
   * Test string in the specified language
   */
  test: string;
};

export type ModelDetails = {
  /**
   * The ID of the model.
   */
  id: string;
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The Unix timestamp of when the model was created.
   */
  created?: number;
  /**
   * The user ID of the owner.
   */
  owned_by?: string;
};

export type ModelResponse = {
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The list of models.
   */
  data: Array<ModelDetails>;
};

export type MyUserDto = {
  /**
   * The user's unique identifier (OID).
   */
  id: string;
  /**
   * The user's name.
   */
  name: string;
  /**
   * The user's email address.
   */
  email: string;
  /**
   * User's profile image in base64.
   */
  profile_image?: string | null;
};

export type PromptTokensDetails = {
  audio_tokens?: number | null;
  cached_tokens?: number | null;
  [key: string]: unknown | (number | null) | (number | null) | undefined;
};

export type RevokeTokenResponse = {
  detail: string;
};

export type ServiceDto = {
  /**
   * The name of the service.
   */
  name: string;
  /**
   * A description of the service.
   */
  description: string;
  /**
   * The icon representing the service.
   */
  icon: string;
  /**
   * The path under which the service is callable in the frontend.
   */
  path: string;
};

export type SuiteDto = {
  /**
   * The services in the suite.
   */
  services: Array<ServiceDto>;
};

export type TextToSpeechRequest = {
  /**
   * The TTS model to use. Available options: 'tts-1' or 'tts-1-hd'.
   */
  model: "tts-1" | "tts-1-hd";
  /**
   * The text to generate audio for. Maximum length is 4096 characters.
   */
  input: string;
  /**
   * The voice to use when generating audio.
   */
  voice:
    | "alloy"
    | "ash"
    | "coral"
    | "echo"
    | "fable"
    | "onyx"
    | "nova"
    | "sage"
    | "shimmer";
  /**
   * The format of the generated audio file. Defaults to 'mp3'.
   */
  response_format?: ("mp3" | "opus" | "aac" | "flac" | "wav" | "pcm") | null;
  /**
   * The speed of the generated audio. Defaults to 1.0. Range: 0.25 to 4.0.
   */
  speed?: number | null;
  [key: string]:
    | unknown
    | ("tts-1" | "tts-1-hd")
    | string
    | (
        | "alloy"
        | "ash"
        | "coral"
        | "echo"
        | "fable"
        | "onyx"
        | "nova"
        | "sage"
        | "shimmer"
      )
    | (("mp3" | "opus" | "aac" | "flac" | "wav" | "pcm") | null)
    | (number | null)
    | undefined;
};

export type ThreadAgentDto = {
  agent_id: string;
  agent_class: string;
};

export type ThreadResponse = {
  id: string;
  name: string;
  users: Array<UserDto>;
  agents: Array<AgentDto>;
};

export type TokenResponse = {
  /**
   * The token ID
   */
  id: string;
  name: string;
  /**
   * Expiry date
   */
  expiry_date: Date;
  /**
   * List of roles granted to the access token
   */
  roles: Array<string>;
};

export type TopLogprob = {
  token: string;
  bytes?: Array<number> | null;
  logprob: number;
  [key: string]: unknown | string | (Array<number> | null) | number | undefined;
};

export type Transcription = {
  text: string;
  [key: string]: unknown | string;
};

export type TranscriptionSegment = {
  id: number;
  avg_logprob: number;
  compression_ratio: number;
  end: number;
  no_speech_prob: number;
  seek: number;
  start: number;
  temperature: number;
  text: string;
  tokens: Array<number>;
  [key: string]: unknown | number | number | string | Array<number>;
};

export type TranscriptionVerbose = {
  duration: number;
  language: string;
  text: string;
  segments?: Array<TranscriptionSegment> | null;
  words?: Array<TranscriptionWord> | null;
  [key: string]:
    | unknown
    | number
    | string
    | (Array<TranscriptionSegment> | null)
    | (Array<TranscriptionWord> | null)
    | undefined;
};

export type TranscriptionWord = {
  end: number;
  start: number;
  word: string;
  [key: string]: unknown | number | string;
};

export type UserDto = {
  /**
   * The user's unique identifier (OID).
   */
  id: string;
  /**
   * The user's name.
   */
  name: string;
  /**
   * The user's email address.
   */
  email: string;
  /**
   * User's profile image in base64.
   */
  profile_image?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

/**
 * Represents an event sent from the server to a user's WebSocket connection, encapsulating
 * details necessary to identify and display the event in a client application.
 *
 * ### Why WSServerEvent?
 * In a real-time system, events generated by agents need to be transmitted to clients over
 * WebSockets. A `WSServerEvent` standardizes the structure of these messages, including:
 * - Agent identifiers and context (thread/display/run).
 * - Event type, name, and ID for classification.
 * - Payload (`event_data`) containing the actual event content.
 *
 * This consistency helps front-end clients parse and handle events uniformly, and aids in
 * debugging or logging outbound messages.
 *
 * ### Conversion from Persisted Events
 * The `from_persisted_event` method rebuilds a `WSServerEvent` from a `PersistedEventEntity`,
 * allowing previously stored events to be replayed or displayed to users.
 */
export type WsServerEvent = {
  /**
   * The agent class responsible for this event.
   */
  agent_class: string;
  /**
   * Unique identifier of the agent instance that produced the event.
   */
  agent_id: string;
  /**
   * Thread identifier linking events to a particular conversation or workflow.
   */
  thread_id: string;
  /**
   * Display session ID, used to group events for the UI.
   */
  display_id: string;
  /**
   * Optional run ID if the event is associated with a particular run.
   */
  run_id?: string | null;
  /**
   * Type of the event (default: 'display_event').
   */
  event_type?: string | null;
  /**
   * Name of the event, indicating its subtype or category.
   */
  event_name: string;
  /**
   * Unique identifier of this event instance.
   */
  event_id: string;
  /**
   * Payload of the event, containing detailed information.
   */
  event_data: {
    [key: string]: unknown;
  };
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/";
};

export type GetHealthResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetSuiteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/suite/";
};

export type GetSuiteResponses = {
  /**
   * Successful Response
   */
  200: SuiteDto;
};

export type GetSuiteResponse = GetSuiteResponses[keyof GetSuiteResponses];

export type GetMyUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/me";
};

export type GetMyUserResponses = {
  /**
   * Successful Response
   */
  200: MyUserDto;
};

export type GetMyUserResponse = GetMyUserResponses[keyof GetMyUserResponses];

export type GetLocaleData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/i18n/my-locale";
};

export type GetLocaleResponses = {
  /**
   * Successful response with user locale information
   */
  200: LocaleResponse;
};

export type GetLocaleResponse = GetLocaleResponses[keyof GetLocaleResponses];

export type GetAllEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/event/";
};

export type GetAllEventsResponses = {
  /**
   * Successful Response
   */
  200: Array<WsServerEvent>;
};

export type GetAllEventsResponse =
  GetAllEventsResponses[keyof GetAllEventsResponses];

export type ListUserThreadsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/thread/";
};

export type ListUserThreadsResponses = {
  /**
   * Successful Response
   */
  200: Array<ThreadResponse>;
};

export type ListUserThreadsResponse =
  ListUserThreadsResponses[keyof ListUserThreadsResponses];

export type CreateThreadData = {
  body: CreateThreadRequest;
  path?: never;
  query?: never;
  url: "/thread/";
};

export type CreateThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateThreadError = CreateThreadErrors[keyof CreateThreadErrors];

export type CreateThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadResponse;
};

export type CreateThreadResponse =
  CreateThreadResponses[keyof CreateThreadResponses];

export type GetThreadData = {
  body?: never;
  path: {
    thread_id: string;
  };
  query?: never;
  url: "/thread/{thread_id}";
};

export type GetThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetThreadError = GetThreadErrors[keyof GetThreadErrors];

export type GetThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadResponse;
};

export type GetThreadResponse = GetThreadResponses[keyof GetThreadResponses];

export type AddAgentToThreadData = {
  body: AddAgentRequest;
  path: {
    thread_id: string;
  };
  query?: never;
  url: "/thread/{thread_id}/agents";
};

export type AddAgentToThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddAgentToThreadError =
  AddAgentToThreadErrors[keyof AddAgentToThreadErrors];

export type AddAgentToThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadResponse;
};

export type AddAgentToThreadResponse =
  AddAgentToThreadResponses[keyof AddAgentToThreadResponses];

export type RemoveAgentFromThreadData = {
  body?: never;
  path: {
    thread_id: string;
    agent_class: string;
    agent_id: string;
  };
  query?: never;
  url: "/thread/{thread_id}/agents/{agent_class}/{agent_id}";
};

export type RemoveAgentFromThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveAgentFromThreadError =
  RemoveAgentFromThreadErrors[keyof RemoveAgentFromThreadErrors];

export type RemoveAgentFromThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadResponse;
};

export type RemoveAgentFromThreadResponse =
  RemoveAgentFromThreadResponses[keyof RemoveAgentFromThreadResponses];

export type AddUserToThreadData = {
  body: AddUserRequest;
  path: {
    thread_id: string;
  };
  query?: never;
  url: "/thread/{thread_id}/users";
};

export type AddUserToThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddUserToThreadError =
  AddUserToThreadErrors[keyof AddUserToThreadErrors];

export type AddUserToThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadResponse;
};

export type AddUserToThreadResponse =
  AddUserToThreadResponses[keyof AddUserToThreadResponses];

export type RemoveUserFromThreadData = {
  body?: never;
  path: {
    thread_id: string;
    remove_user_id: string;
  };
  query?: never;
  url: "/thread/{thread_id}/users/{remove_user_id}";
};

export type RemoveUserFromThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveUserFromThreadError =
  RemoveUserFromThreadErrors[keyof RemoveUserFromThreadErrors];

export type RemoveUserFromThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadResponse;
};

export type RemoveUserFromThreadResponse =
  RemoveUserFromThreadResponses[keyof RemoveUserFromThreadResponses];

export type GetAgentData = {
  body?: never;
  path: {
    agent_class: string;
    agent_id: string;
  };
  query?: never;
  url: "/agent/{agent_class}/{agent_id}";
};

export type GetAgentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
  /**
   * Successful Response
   */
  200: AgentDto;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type DiscoverAgentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agent/discover";
};

export type DiscoverAgentsResponses = {
  /**
   * Successful Response
   */
  200: Array<AgentDto>;
};

export type DiscoverAgentsResponse =
  DiscoverAgentsResponses[keyof DiscoverAgentsResponses];

export type ListTokensEndpointData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/tokens/";
};

export type ListTokensEndpointResponses = {
  /**
   * Successful Response
   */
  200: Array<TokenResponse>;
};

export type ListTokensEndpointResponse =
  ListTokensEndpointResponses[keyof ListTokensEndpointResponses];

export type CreateTokenEndpointData = {
  body: CreateTokenRequest;
  path?: never;
  query?: never;
  url: "/tokens/";
};

export type CreateTokenEndpointErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTokenEndpointError =
  CreateTokenEndpointErrors[keyof CreateTokenEndpointErrors];

export type CreateTokenEndpointResponses = {
  /**
   * Successful Response
   */
  201: CreateTokenResponse;
};

export type CreateTokenEndpointResponse =
  CreateTokenEndpointResponses[keyof CreateTokenEndpointResponses];

export type RevokeTokenEndpointData = {
  body?: never;
  path: {
    token_id: string;
  };
  query?: never;
  url: "/tokens/{token_id}";
};

export type RevokeTokenEndpointErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RevokeTokenEndpointError =
  RevokeTokenEndpointErrors[keyof RevokeTokenEndpointErrors];

export type RevokeTokenEndpointResponses = {
  /**
   * Successful Response
   */
  200: RevokeTokenResponse;
};

export type RevokeTokenEndpointResponse =
  RevokeTokenEndpointResponses[keyof RevokeTokenEndpointResponses];

export type GetModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/openai/models";
};

export type GetModelsResponses = {
  /**
   * Successful Response
   */
  200: ModelResponse;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type GetModelData = {
  body?: never;
  path: {
    full_path: string;
  };
  query?: never;
  url: "/openai/models/{full_path}";
};

export type GetModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetModelError = GetModelErrors[keyof GetModelErrors];

export type GetModelResponses = {
  /**
   * Successful Response
   */
  200: ModelDetails;
};

export type GetModelResponse = GetModelResponses[keyof GetModelResponses];

export type GetEmbeddingsData = {
  body: EmbeddingsRequest;
  path?: never;
  query?: never;
  url: "/openai/embeddings";
};

export type GetEmbeddingsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEmbeddingsError = GetEmbeddingsErrors[keyof GetEmbeddingsErrors];

export type GetEmbeddingsResponses = {
  /**
   * Successful Response
   */
  200: EmbeddingsResponse;
};

export type GetEmbeddingsResponse =
  GetEmbeddingsResponses[keyof GetEmbeddingsResponses];

export type ChatCompletionData = {
  body: ChatCompletionRequest;
  path?: never;
  query?: never;
  url: "/openai/chat/completions";
};

export type ChatCompletionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChatCompletionError =
  ChatCompletionErrors[keyof ChatCompletionErrors];

export type ChatCompletionResponses = {
  /**
   * Successful Response
   */
  200: ChatCompletion;
};

export type ChatCompletionResponse =
  ChatCompletionResponses[keyof ChatCompletionResponses];

export type GenerateImageData = {
  body: ImageGenerationRequest;
  path?: never;
  query?: never;
  url: "/openai/images/generations";
};

export type GenerateImageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateImageError = GenerateImageErrors[keyof GenerateImageErrors];

export type GenerateImageResponses = {
  /**
   * Successful Response
   */
  200: ImagesResponse;
};

export type GenerateImageResponse =
  GenerateImageResponses[keyof GenerateImageResponses];

export type CreateTranscriptionData = {
  body: BodyCreateTranscriptionOpenaiAudioTranscriptionsPost;
  path?: never;
  query?: never;
  url: "/openai/audio/transcriptions";
};

export type CreateTranscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTranscriptionError =
  CreateTranscriptionErrors[keyof CreateTranscriptionErrors];

export type CreateTranscriptionResponses = {
  /**
   * Successful Response
   */
  200: Transcription | TranscriptionVerbose | string;
};

export type CreateTranscriptionResponse =
  CreateTranscriptionResponses[keyof CreateTranscriptionResponses];

export type CreateSpeechData = {
  body: TextToSpeechRequest;
  path?: never;
  query?: never;
  url: "/openai/audio/speech";
};

export type CreateSpeechErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSpeechError = CreateSpeechErrors[keyof CreateSpeechErrors];

export type CreateSpeechResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://${string}/api/v1` | (string & {});
};
