services:
  docling:
    image: my-docling-serve:latest
    container_name: docling-serve
    ports:
      - 5001:5001
    environment:
      - DOCLING_SERVE_ARTIFACTS_PATH=/app/models
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]