# This file is auto-generated from a Jinja2 template.
# DO NOT EDIT THIS FILE DIRECTLY.
#
# To make changes, edit deployment/templates/configs/milvus-watchdog.Dockerfile.j2

# Alpine plus curl, deliberately: the watchdog restarts the vector database, so it is
# built here from a base already used by etcd-init rather than pulled from a
# third-party project that would first have to be mirrored into our registry.
FROM alpine:3.19

RUN apk add --no-cache curl

COPY watchdog.sh /usr/local/bin/watchdog.sh

RUN chmod +x /usr/local/bin/watchdog.sh

ENTRYPOINT ["/bin/sh", "/usr/local/bin/watchdog.sh"]
