#!/bin/sh
# This file is auto-generated from a Jinja2 template.
# DO NOT EDIT THIS FILE DIRECTLY.
#
# To make changes, edit deployment/templates/configs/milvus-watchdog.sh.j2
#
# Restarts Milvus once Docker has reported it unhealthy for long enough that it is
# not going to recover on its own.
#
# Docker's restart policy acts on a process exit, never on a health status, so
# `restart: always` cannot clear the failure this exists for: Milvus running with its
# proxy, querynode and streamingnode permanently unregistered, answering
# "Milvus Proxy is not ready yet" to every client while the container stays up and
# `docker ps` keeps calling it Up. Observed on staging on 2026-09-03: unhealthy from
# 07:19 until a manual restart at 08:15, with every RAG answer failing in between.
# A restart is what cleared it, which is the whole reason this can be automated.

set -eu

DOCKER_API="http://docker-socket-proxy-heal:2375"
CONTAINER_NAME="milvus"

# These numbers only decide how long a *confirmed* unhealthy verdict must persist.
# Milvus needs minutes rather than seconds to become ready, and the container's own
# healthcheck already absorbs that with its start_period, so this loop never sees a
# starting container as unhealthy. The cooldown is deliberately longer than that
# start_period: the first poll after a restart must read a fresh grace window instead
# of the verdict the restart was meant to clear.
POLL_INTERVAL_SECONDS=30
UNHEALTHY_POLLS_BEFORE_RESTART=4
COOLDOWN_SECONDS=420

log() {
    echo "[milvus-watchdog] $(date -u '+%Y-%m-%dT%H:%M:%SZ') $1"
}

milvus_is_unhealthy() {
    # The name filter is anchored so it cannot also match this watchdog's own container.
    if ! unhealthy_matches=$(
        curl -fsS --max-time 10 --get \
            --data-urlencode "filters={\"health\":[\"unhealthy\"],\"name\":[\"^/${CONTAINER_NAME}\$\"]}" \
            "${DOCKER_API}/containers/json"
    ); then
        # Being unable to see the container is not evidence that it is broken, and
        # restarting on our own blindness is how a watchdog becomes the outage.
        log "docker api unreachable, skipping this poll"
        return 1
    fi

    [ "${unhealthy_matches}" != "[]" ]
}

log "watching ${CONTAINER_NAME}; restarting after $((POLL_INTERVAL_SECONDS * UNHEALTHY_POLLS_BEFORE_RESTART))s of confirmed unhealthy"

unhealthy_polls=0

while true; do
    sleep "${POLL_INTERVAL_SECONDS}"

    if ! milvus_is_unhealthy; then
        unhealthy_polls=0
        continue
    fi

    unhealthy_polls=$((unhealthy_polls + 1))
    log "${CONTAINER_NAME} reported unhealthy (${unhealthy_polls}/${UNHEALTHY_POLLS_BEFORE_RESTART})"

    if [ "${unhealthy_polls}" -lt "${UNHEALTHY_POLLS_BEFORE_RESTART}" ]; then
        continue
    fi

    log "restarting ${CONTAINER_NAME}"
    if curl -fsS --max-time 120 -X POST "${DOCKER_API}/containers/${CONTAINER_NAME}/restart"; then
        log "restart accepted, holding off for ${COOLDOWN_SECONDS}s"
    else
        log "restart request failed, retrying after ${COOLDOWN_SECONDS}s"
    fi

    unhealthy_polls=0
    sleep "${COOLDOWN_SECONDS}"
done
