http:
  middlewares:
    security-headers:
      headers:
        sslRedirect: false
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        customFrameOptionsValue: "DENY"
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
