from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field

from openinference.semconv.trace import MessageAttributes


class Message(BaseModel):
    role: str = Field(
        ...,
        description="The role of the message, such as 'user', 'assistant', or 'system'.",
    )
    content: Optional[str] = Field(None, description="The content of the message.")
    name: Optional[str] = Field(None, description="The name of the function or agent generating the message.")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="List of tool calls generated by the model, such as function calls.",
    )
    function_call_name: Optional[str] = Field(None, description="The name of the function being called in the message.")
    function_call_arguments_json: Optional[Dict[str, Any]] = Field(
        None,
        description="JSON representing arguments passed to the function during a function call.",
    )
    tool_call_id: Optional[str] = Field(None, description="The ID of the tool call, if applicable.")

    def to_semantic_convention(self, key: str, i: int) -> Dict[str, str]:
        return {
            f"{key}.{i}.{MessageAttributes.MESSAGE_ROLE}": self.role,
            f"{key}.{i}.{MessageAttributes.MESSAGE_CONTENT}": self.content,
            f"{key}.{i}.{MessageAttributes.MESSAGE_NAME}": self.name,
            f"{key}.{i}.{MessageAttributes.MESSAGE_TOOL_CALLS}": self.tool_calls,
            f"{key}.{i}.{MessageAttributes.MESSAGE_FUNCTION_CALL_NAME}": self.function_call_name,
            f"{key}.{i}.{MessageAttributes.MESSAGE_FUNCTION_CALL_ARGUMENTS_JSON}": self.function_call_arguments_json,
            f"{key}.{i}.{MessageAttributes.MESSAGE_TOOL_CALL_ID}": self.tool_call_id,
        }
