import json
from typing import Annotated, Any, Literal

from llama_index.core.base.llms.types import (
    AudioBlock,
    ChatMessage,
    ImageBlock,
    TextBlock,
)
from llama_index.core.base.llms.types import (
    ContentBlock as LlamaIndexContentBlock,
)
from openinference.semconv.trace import AudioAttributes, ImageAttributes, MessageAttributes, MessageContentAttributes
from pydantic import BaseModel, Field, computed_field


class TextContent(BaseModel):
    type: Annotated[Literal["text"], Field(..., description="Block type, must be 'text' for TextContent")] = "text"
    text: Annotated[str, Field(..., description="Text content of the message")]


class ImageContent(BaseModel):
    type: Annotated[Literal["image"], Field(..., description="Block type, must be 'image' for ImageContent")] = "image"
    url: Annotated[
        str | None, Field(..., description="Base64 encoded image or url pointing to externally stored image")
    ] = None


class AudioContent(BaseModel):
    type: Annotated[Literal["audio"], Field(..., description="Block type, must be 'audio' for AudioContent")] = "audio"
    url: Annotated[
        str | None, Field(..., description="Base64 encoded audio or url pointing to externally stored audio")
    ] = None
    mime_type: Annotated[str | None, "Mime type, most often 'audio/wav'"] = None


ContentBlock = TextContent | ImageContent | AudioContent


class Message(BaseModel):
    role: Annotated[
        str,
        Field(
            description="The role of the message, such as 'user', 'assistant', or 'system'.",
        ),
    ]
    name: Annotated[str | None, Field(description="The name of the function or agent generating the message.")] = None
    tool_calls: Annotated[
        list[dict[str, Any]] | None,
        Field(
            description="List of tool calls generated by the model, such as function calls.",
        ),
    ] = None
    function_call_name: Annotated[
        str | None, Field(description="The name of the function being called in the message.")
    ] = None
    function_call_arguments_json: Annotated[
        dict[str, Any] | None,
        Field(
            description="JSON representing arguments passed to the function during a function call.",
        ),
    ] = None
    tool_call_id: Annotated[str | None, Field(description="The ID of the tool call, if applicable.")] = None
    contents: Annotated[
        list[ContentBlock] | None,
        Field(
            description="The message contents as an array of content blocks (text, image, audio).",
        ),
    ] = None

    @computed_field
    @property
    def content(self) -> str:
        content = ""
        for block in self.contents:
            if isinstance(block, TextContent):
                content += block.text
        return content

    @classmethod
    def from_string(cls, role: str, content: str, name: str | None = None) -> "Message":
        return cls(role=role, contents=[TextContent(text=content)], name=name)

    def to_semantic_convention(self, key: str, i: int) -> dict[str, Any]:
        result: dict[str, Any] = {}
        result[f"{key}.{i}.{MessageAttributes.MESSAGE_ROLE}"] = self.role
        if self.content is not None:
            result[f"{key}.{i}.{MessageAttributes.MESSAGE_CONTENT}"] = self.content
        if self.name is not None:
            result[f"{key}.{i}.{MessageAttributes.MESSAGE_NAME}"] = self.name
        if self.tool_calls is not None:
            result[f"{key}.{i}.{MessageAttributes.MESSAGE_TOOL_CALLS}"] = json.dumps(self.tool_calls)
        if self.function_call_name is not None:
            result[f"{key}.{i}.{MessageAttributes.MESSAGE_FUNCTION_CALL_NAME}"] = self.function_call_name
        if self.function_call_arguments_json is not None:
            result[f"{key}.{i}.{MessageAttributes.MESSAGE_FUNCTION_CALL_ARGUMENTS_JSON}"] = json.dumps(
                self.function_call_arguments_json
            )
        if self.tool_call_id is not None:
            result[f"{key}.{i}.{MessageAttributes.MESSAGE_TOOL_CALL_ID}"] = self.tool_call_id

        # flatten contents
        if not self.contents:
            return result

        for j, block in enumerate(self.contents):
            base = f"{key}.{i}.{MessageAttributes.MESSAGE_CONTENTS}.{j}"
            result[f"{base}.{MessageContentAttributes.MESSAGE_CONTENT_TYPE}"] = block.type
            if isinstance(block, TextContent):
                result[f"{base}.{MessageContentAttributes.MESSAGE_CONTENT_TEXT}"] = block.text
            elif isinstance(block, ImageContent):
                if block.url:
                    result[f"{base}.{MessageContentAttributes.MESSAGE_CONTENT_IMAGE}.{ImageAttributes.IMAGE_URL}"] = (
                        block.url
                    )
            elif isinstance(block, AudioContent):
                if block.url:
                    result[f"{base}.{AudioAttributes.AUDIO_URL}"] = block.url
                if block.mime_type:
                    result[f"{base}.{AudioAttributes.AUDIO_MIME_TYPE}"] = block.mime_type

        return result

    @classmethod
    def from_llama_index(cls, msg: ChatMessage) -> "Message":
        function_call: dict[str, Any] = msg.additional_kwargs.get("function_call", {}) or {}
        message_dict: dict[str, Any] = {
            "role": msg.role.value,
            "name": msg.additional_kwargs.get("name"),
            "tool_calls": msg.additional_kwargs.get("tool_calls"),
            "function_call_name": function_call.get("name"),
            "function_call_arguments_json": function_call.get("arguments"),
            "tool_call_id": msg.additional_kwargs.get("tool_call_id"),
        }
        if not msg.blocks:
            return cls(**{k: v for k, v in message_dict.items() if v is not None})

        contents: list[ContentBlock] = []
        for block in msg.blocks:
            cb = cls._process_block(block)
            if cb:
                contents.append(cb)
        if contents:
            message_dict["contents"] = contents
        return cls(**{k: v for k, v in message_dict.items() if v is not None})

    def to_llama_index(self) -> ChatMessage:
        """Converts a message to llama index"""
        blocks: list[LlamaIndexContentBlock] = []
        for block in self.contents or []:
            cb = self._process_block_backwards(block)
            if cb:
                blocks.append(cb)
        return ChatMessage(role=self.role, blocks=blocks)

    @staticmethod
    def _process_block(block: Any) -> ContentBlock | None:
        if isinstance(block, TextBlock) or getattr(block, "block_type", None) == "text":
            text = getattr(block, "text", str(block))
            return TextContent(text=text)
        if isinstance(block, ImageBlock) or getattr(block, "block_type", None) == "image":
            url = getattr(block, "url", None)
            return ImageContent(url=str(url) if url else None)
        if isinstance(block, AudioBlock) or getattr(block, "block_type", None) == "audio":
            url = getattr(block, "url", None)
            mime = f"audio/{getattr(block, 'format', '')}" if getattr(block, "format", None) else None
            return AudioContent(url=str(url) if url else None, mime_type=mime)
        return None

    @staticmethod
    def _process_block_backwards(block: ContentBlock) -> Any:
        if isinstance(block, TextContent):
            return TextBlock(text=block.text)
        if isinstance(block, ImageContent):
            return ImageBlock(url=block.url)
        if isinstance(block, AudioContent):
            return AudioBlock(url=block.url, format=block.mime_type.split("/")[1])
