### Test: Send Events
WEBSOCKET ws://localhost:8000/event/ws
Content-Type: application/json

{
  "thread_id":"674efdcf0d610d191262a26c",
  "display_id":"675b1d2ef8c3388b25b4644e",
  "event":{
    "_type":"UserMessageEvent",
    "event_id":"675b1d2ef8c3388b25b4644f",
    "created_at":1734024494985000000,
    "content":"test"
  }
}
