sonar.projectKey=aihub-core_process-core
sonar.organization=bbv-ai

# This is the name and version displayed in the SonarCloud UI
sonar.projectName=Process Core
sonar.projectVersion=1.0

sonar.sources=swiss_ai_hub
sonar.tests=swiss_ai_hub
sonar.test.inclusions=**/test_*.py

# Encoding of the source code
sonar.sourceEncoding=UTF-8
