sonar.projectKey=ai-hub_aihub-web
sonar.organization=bbv-ai

# This is the name and version displayed in the SonarCloud UI
sonar.projectName=Web Core
sonar.projectVersion=1.0

sonar.sources=aihub_web/src
sonar.tests=aihub_web/src
sonar.test.inclusions=aihub_web/src/**/*.spec.*

# Encoding of the source code
sonar.sourceEncoding=UTF-8
