[tool.poetry]
name = "aihub_pipeline"
version = "v0.1.0"
description = "pipeline core"
authors = [
    "Joel Barmettler <joel.barmettler@bbv.ch>",
    "Marius Högger <marius.hoegger@bbv.ch>",
    "Michèle Fundneider <michele.fundneider@bbv.ch>",
]
license = "Proprietary"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.12"
lib_core = { git = "https://github.com/bbvch-ai/aihub-core.git", tag = "v0.1.0", subdirectory = "lib_core" }
dagster-webserver = "^1.8.13"
dagster-postgres = "^0.24.13"
dagster-azure = "^0.24.13"
llama-index-readers-file = "^0.2.2"
matplotlib = "^3.9.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.24.0"
ruff = "^0.8.1"
mypy = "^1.13.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"