[tool.poetry]
name = "aihub_pipeline"
version = "v0.16.0"
description = "pipeline core"
authors = [
    "Joel Barmettler <joel.barmettler@bbv.ch>",
    "Marius Högger <marius.hoegger@bbv.ch>",
    "Michèle Fundneider <michele.fundneider@bbv.ch>",
]
license = "Proprietary"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.12"
dagster-webserver = "^1.9.6"
dagster-postgres = "^0.25.6"
dagster-azure = "^0.25.6"
llama-index-readers-file = "^0.4.1"
matplotlib = "^3.9.2"

[tool.poetry.dependencies.aihub_lib]
path = "../aihub_lib"
develop = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.24.0"
ruff = "^0.8.1"
mypy = "^1.13.0"
isort = "^5.13.2"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = 'py311'

[tool.ruff.lint]
extend-ignore = ["E203"]

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
