#!/bin/sh
# This file is auto-generated from a Jinja2 template.
# DO NOT EDIT THIS FILE DIRECTLY.
#
# To make changes, edit deployment/templates/configs/s3-entrypoint.sh.j2
set -e

# SeaweedFS S3 credentials
SEAWEEDFS_S3_USER=${SEAWEEDFS_S3_USER}
SEAWEEDFS_S3_PASSWORD=${SEAWEEDFS_S3_PASSWORD}

S3_PORT=${S3_PORT:-9000}
S3_FILER=${S3_FILER:-seaweedfs-filer:8888}
S3_BIND_IP=${S3_BIND_IP:-0.0.0.0}
S3_ALLOW_EMPTY_FOLDER=${S3_ALLOW_EMPTY_FOLDER:-true}

# Generate s3.json dynamically from environment variables
cat > /tmp/s3.json <<EOF
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "${SEAWEEDFS_S3_USER}",
          "secretKey": "${SEAWEEDFS_S3_PASSWORD}"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "ReadAcp",
        "Write",
        "WriteAcp",
        "List",
        "Tagging"
      ]
    }
  ]
}
EOF

echo "Starting SeaweedFS S3 Gateway"
echo "  - Port: ${S3_PORT}"
echo "  - Filer: ${S3_FILER}"
echo "  - User: ${SEAWEEDFS_S3_USER}"

# Build command without quotes around the asterisk
CMD_ARGS=""
CMD_ARGS="${CMD_ARGS} -filer=${S3_FILER}"
CMD_ARGS="${CMD_ARGS} -port=${S3_PORT}"
CMD_ARGS="${CMD_ARGS} -ip.bind=${S3_BIND_IP}"
CMD_ARGS="${CMD_ARGS} -config=/tmp/s3.json"
CMD_ARGS="${CMD_ARGS} -allowEmptyFolder=${S3_ALLOW_EMPTY_FOLDER}"
CMD_ARGS="${CMD_ARGS} -allowedOrigins=*"

echo "Executing: weed s3 ${CMD_ARGS}"
exec weed s3 ${CMD_ARGS}