{{- if .Values.oauth2proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aihub.fullname" (dict "component" "oauth2proxy" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2proxy
spec:
  replicas: {{ .Values.oauth2proxy.replicas }}
  selector:
    matchLabels:
      {{- include "aihub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: oauth2proxy
  template:
    metadata:
      labels:
        {{- include "aihub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: oauth2proxy
    spec:
      securityContext:
        {{- include "aihub.podSecurityContext" . | nindent 8 }}
      containers:
      - name: oauth2proxy
        image: "{{ .Values.oauth2proxy.image.repository }}:{{ required "oauth2proxy.image.tag is required" .Values.oauth2proxy.image.tag }}"
        imagePullPolicy: {{ .Values.oauth2proxy.image.pullPolicy }}
        securityContext:
          {{- include "aihub.securityContext" . | nindent 10 }}
        env:
        {{- include "aihub.commonEnv" . | nindent 8 }}
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: "$(OAUTH_AUTHORITY_URL)/v2.0"
        envFrom:
        # Non-sensitive environment variables from OAuth2Proxy ConfigMap
        - configMapRef:
            name: {{ include "aihub.fullname" (dict "component" "oauth2proxy-env" "context" .) }}
        # Sensitive environment variables from OAuth2Proxy Secret
        - secretRef:
            name: {{ include "aihub.fullname" (dict "component" "oauth2proxy-secret" "context" .) }}
        ports:
        - containerPort: 4180
          name: oauth2proxy
        resources:
          {{- toYaml .Values.oauth2proxy.resources | nindent 10 }}
{{- end }}
