{{- if .Values.oauth2proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aihub.fullname" (dict "component" "oauth2proxy-secret" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2proxy
type: Opaque
data:
  # OAuth2Proxy credentials from oauth2proxy service
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.oauth2proxy.env.OAUTH_CLIENT_ID | b64enc }}
  OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: {{ .Values.oauth2proxy.env.OAUTH_PROVIDER_NAME | b64enc }}
  OAUTH_AUTHORITY_URL: {{ .Values.oauth2proxy.env.OAUTH_AUTHORITY_URL | b64enc }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.oauth2proxy.env.OAUTH_COOKIE_SECRET | b64enc }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.oauth2proxy.env.OAUTH_CLIENT_SECRET | b64enc }}
{{- end }}
