#!/bin/bash
# This file is auto-generated from a Jinja2 template.
# DO NOT EDIT THIS FILE DIRECTLY.
#
# To make changes, edit deployment/templates/configs/pg-init-multiple-dbs.sh.j2
set -e
set -u

function create_db_if_not_exists() {
  local db="$1"
  echo "Checking if database '$db' exists..."
  if psql -U "$POSTGRES_USER" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${db}'" | grep -q 1; then
    echo "Database '$db' already exists, skipping."
  else
    psql -U "$POSTGRES_USER" -d postgres -c "CREATE DATABASE \"$db\";"
    echo "Database '$db' created successfully!"
  fi
}
if [ -n "${POSTGRES_MULTIPLE_DATABASES:-}" ]; then
  echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
  for db in $(echo "$POSTGRES_MULTIPLE_DATABASES" | tr ',' ' '); do
    create_db_if_not_exists "$db"
  done
  echo "All requested databases handled."
fi

# pg_repack extension — required by the maintenance subsystem in
# packages/backup (postgres_repack handler). Installed in the custom postgres
# image (infra/deployment/docker/postgres/Dockerfile); enabled per-DB here.
# IF NOT EXISTS keeps this idempotent across restarts.
echo "Enabling pg_repack extension in dagster database..."
psql -U "$POSTGRES_USER" -d dagster -c "CREATE EXTENSION IF NOT EXISTS pg_repack;" \
  || echo "pg_repack extension not available (image may not include postgresql-17-repack); skipping"
