receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    metrics: # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/dockerstatsreceiver/documentation.md
      container.cpu.utilization:
        enabled: true
      container.cpu.usage.total:
        enabled: true
      container.cpu.logical.count:
        enabled: true
      container.memory.percent:
        enabled: true
      container.memory.usage.limit:
        enabled: true
      container.memory.usage.total:
        enabled: true
      container.network.io.usage.rx_bytes:
        enabled: true
      container.network.io.usage.tx_bytes:
        enabled: true
      container.network.io.usage.rx_dropped:
        enabled: true
      container.network.io.usage.tx_dropped:
        enabled: true
      container.blockio.io_service_bytes_recursive:
        enabled: true
      container.restarts:
        enabled: true
  dockerevents:
    endpoint: unix:///var/run/docker.sock
    filters:
      type: container
      event:
        - health_status
        - health_status:healthy
        - health_status:unhealthy
processors:
  batch:

  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false


  resource/docker:
    attributes:
      - key: service.name
        from_attribute: container.name
        action: upsert
      - key: service.version
        from_attribute: container.image.tag
        action: upsert

  transform/health_logs:
    log_statements:
      - context: log
        statements:
          # Just pass through the basic info
          - set(attributes["container_name"], body["Actor"]["Attributes"]["name"]) where body["Type"] == "container"
          - set(attributes["docker_action"], body["Action"]) where body["Type"] == "container"
          - set(attributes["event_type"], "docker_health") where body["Type"] == "container"
          - set(severity_text, "INFO")


exporters:
  otlp/signoz:
    endpoint: "${SIGNOZ_INGESTION_CLOUD_ENDPOINT}"
    headers:
      signoz-ingestion-key: "${SIGNOZ_INGESTION_KEY}"
    tls:
      insecure: false

  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/signoz]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/signoz]
    metrics/docker:
      receivers: [ docker_stats ]
      processors: [ resourcedetection/docker, resource/docker, batch ]
      exporters: [ otlp/signoz ]
    logs/docker_health:
      receivers: [dockerevents]
      processors: [transform/health_logs, batch]
      exporters: [otlp/signoz, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/signoz]