from typing import Dict, Optional

from pydantic import BaseModel, Field

from lib_core.nats.topic_managers.TopicManager import TopicManager
from lib_core.persistence.messaging.entities.PersistedEventEntity import PersistedEventEntity


class WSServerEvent(BaseModel):
    """
    Represents an event sent from the server to a user's WebSocket connection, encapsulating
    details necessary to identify and display the event in a client application.

    ### Why WSServerEvent?
    In a real-time system, events generated by agents need to be transmitted to clients over
    WebSockets. A `WSServerEvent` standardizes the structure of these messages, including:
    - Agent identifiers and context (thread/display/run).
    - Event type, name, and ID for classification.
    - Payload (`event_data`) containing the actual event content.

    This consistency helps front-end clients parse and handle events uniformly, and aids in
    debugging or logging outbound messages.

    ### Conversion from Persisted Events
    The `from_persisted_event` method rebuilds a `WSServerEvent` from a `PersistedEventEntity`,
    allowing previously stored events to be replayed or displayed to users.
    """

    agent_class: str = Field(..., description="The agent class responsible for this event.")
    agent_id: str = Field(..., description="Unique identifier of the agent instance that produced the event.")
    thread_id: str = Field(..., description="Thread identifier linking events to a particular conversation or workflow.")
    display_id: str = Field(..., description="Display session ID, used to group events for the UI.")
    run_id: Optional[str] = Field(None, description="Optional run ID if the event is associated with a particular run.")
    event_type: Optional[str] = Field(TopicManager.DISPLAY_EVENT, description="Type of the event (default: 'display_event').")
    event_name: str = Field(..., description="Name of the event, indicating its subtype or category.")
    event_id: str = Field(..., description="Unique identifier of this event instance.")
    event_data: Dict = Field(..., description="Payload of the event, containing detailed information.")

    @classmethod
    def from_persisted_event(cls, persisted_event: PersistedEventEntity) -> 'WSServerEvent':
        """
        Construct a WSServerEvent from a PersistedEventEntity, converting persisted event data
        into a client-ready format.
        """
        return cls(
            agent_class=persisted_event.agent_class,
            agent_id=persisted_event.agent_id,
            thread_id=persisted_event.thread_id,
            display_id=persisted_event.display_id,
            run_id=persisted_event.run_id,
            event_type=persisted_event.event_type,
            event_name=persisted_event.event_name,
            event_id=persisted_event.event_id,
            event_data=persisted_event.event_data,
        )
