{{- if .Values.openWebui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aihub.deploymentName" (dict "component" "openwebui" "Release" .Release) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: openwebui
spec:
  replicas: {{ .Values.openWebui.replicas }}
  selector:
    matchLabels:
      {{- include "aihub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: openwebui
  template:
    metadata:
      labels:
        {{- include "aihub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: openwebui
    spec:
      securityContext:
        {{- include "aihub.podSecurityContext" . | nindent 8 }}
      tolerations:
        {{- include "aihub.globalTolerations" . | nindent 8 }}
      containers:
      - name: openwebui
        image: {{ .Values.openWebui.image.repository }}:{{ .Values.openWebui.image.tag }}
        imagePullPolicy: {{ .Values.openWebui.image.pullPolicy }}
        securityContext:
          {{- include "aihub.securityContext" . | nindent 10 }}
        env:
        {{- include "aihub.commonEnv" . | nindent 8 }}
        - name: WEBUI_NAME
          value: "Swiss AI-Hub"
        - name: WEBUI_URL
          value: "https://openwebui.{{ .Values.global.domain }}"
        - name: DEFAULT_LOCALE
          value: "de"
        - name: ENABLE_BASE_MODELS_CACHE
          value: "True"
        - name: ENV
          value: "prod"
        - name: GLOBAL_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: LOG_LEVEL
        - name: ENABLE_COMMUNITY_SHARING
          value: "False"
        - name: ENABLE_USER_WEBHOOKS
          value: "False"
        - name: ENABLE_LOGIN_FORM
          value: "False"
        - name: ENABLE_FORWARD_USER_INFO_HEADERS
          value: "True"
        - name: ENABLE_VERSION_UPDATE_CHECK
          value: "False"
        - name: ENABLE_OTEL
          value: "False"
        - name: WEBUI_AUTH
          value: "True"
        - name: DEFAULT_USER_ROLE
          value: "user"
        - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
          value: "True"
        - name: ENABLE_API_KEY
          value: "False"
        - name: WEBUI_SESSION_COOKIE_SAME_SITE
          value: "lax"
        - name: WEBUI_SESSION_COOKIE_SECURE
          value: "False"
        - name: ENABLE_OAUTH_SIGNUP
          value: "True"
        - name: OAUTH_PROVIDER_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: OAUTH_PROVIDER_NAME
        - name: OAUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: OAUTH_CLIENT_ID
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: OAUTH_CLIENT_SECRET
        - name: OPENID_PROVIDER_URL
          value: "$(OAUTH_AUTHORITY_URL)/v2.0/.well-known/openid-configuration"
        - name: OAUTH_AUTHORITY_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: OAUTH_AUTHORITY_URL
        - name: OPENID_REDIRECT_URI
          value: "https://openwebui.{{ .Values.global.domain }}/oauth/oidc/callback"
        - name: OAUTH_ALLOWED_DOMAINS
          value: "*"
        - name: OAUTH_SCOPES
          value: "openid email profile"
        - name: OAUTH_TIMEOUT
          value: "60"
        - name: OAUTH_CODE_CHALLENGE_METHOD
          value: "S256"
        - name: OAUTH_USERNAME_CLAIM
          value: "name"
        - name: OAUTH_PICTURE_CLAIM
          value: "picture"
        - name: OAUTH_EMAIL_CLAIM
          value: "email"
        - name: OAUTH_GROUP_CLAIM
          value: "email"
        - name: STORAGE_PROVIDER
          value: "s3"
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: MINIO_ROOT_USER
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: MINIO_ROOT_PASSWORD
        - name: S3_REGION_NAME
          value: "us-east-1"
        - name: S3_BUCKET_NAME
          value: "open-webui"
        - name: S3_ENDPOINT_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "minio" "Release" .Release) }}:9000"
        - name: OPENAI_API_BASE_URL
          value: ""
        - name: OPENAI_API_KEY
          value: ""
        - name: RAG_OPENAI_API_BASE_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "api" "Release" .Release) }}:8000/api/v1"
        - name: RAG_OPENAI_API_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: SUPERUSER_TOKEN
        - name: AUDIO_STT_OPENAI_API_BASE_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "api" "Release" .Release) }}:8000/api/v1"
        - name: AUDIO_STT_OPENAI_API_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: SUPERUSER_TOKEN
        - name: AUDIO_TTS_OPENAI_API_BASE_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "api" "Release" .Release) }}:8000/api/v1"
        - name: AUDIO_TTS_OPENAI_API_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: SUPERUSER_TOKEN
        - name: ENABLE_IMAGE_GENERATION
          value: "True"
        - name: IMAGES_OPENAI_API_BASE_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "api" "Release" .Release) }}:8000/api/v1"
        - name: IMAGES_OPENAI_API_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: SUPERUSER_TOKEN
        - name: MODELS_CACHE_TTL
          value: "60"
        - name: TASK_MODEL
          value: "azure/gpt-4o-mini"
        - name: TASK_MODEL_EXTERNAL
          value: "azure/gpt-4o-mini"
        - name: DATABASE_TYPE
          value: "postgres"
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: POSTGRES_PASSWORD
        - name: DATABASE_HOST
          value: "{{ include "aihub.serviceName" (dict "component" "postgres" "Release" .Release) }}"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "openwebui"
        - name: REDIS_URL
          value: "redis://{{ include "aihub.serviceName" (dict "component" "redis" "Release" .Release) }}:6379/1"
        - name: REDIS_KEY_PREFIX
          value: "open-webui"
        - name: UVICORN_WORKERS
          value: "1"
        - name: ENABLE_WEBSOCKET_SUPPORT
          value: "True"
        - name: WEBSOCKET_MANAGER
          value: "redis"
        - name: WEBSOCKET_REDIS_URL
          value: "redis://{{ include "aihub.serviceName" (dict "component" "redis" "Release" .Release) }}:6379/1"
        - name: THREAD_POOL_SIZE
          value: "32"
        - name: CORS_ALLOW_ORIGIN
          value: "*"
        - name: ENABLE_ADMIN_EXPORT
          value: "True"
        - name: ENABLE_ADMIN_CHAT_ACCESS
          value: "True"
        - name: SHOW_ADMIN_DETAILS
          value: "True"
        - name: ADMIN_EMAIL
          value: "admin@ai-hub.bbv.ch"
        - name: CODE_EXECUTION_ENGINE
          value: "jupyter"
        - name: CODE_EXECUTION_JUPYTER_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "jupyter" "Release" .Release) }}:8888"
        - name: CODE_EXECUTION_JUPYTER_AUTH
          value: "token"
        - name: CODE_EXECUTION_JUPYTER_AUTH_TOKEN
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: JUPYTER_TOKEN
        - name: CODE_INTERPRETER_ENGINE
          value: "jupyter"
        - name: CODE_INTERPRETER_JUPYTER_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "jupyter" "Release" .Release) }}:8888"
        - name: CODE_INTERPRETER_JUPYTER_AUTH
          value: "token"
        - name: CODE_INTERPRETER_JUPYTER_AUTH_TOKEN
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: JUPYTER_TOKEN
        - name: VECTOR_DB
          value: "milvus"
        - name: MILVUS_DB
          value: "default"
        - name: MILVUS_URI
          value: "http://{{ include "aihub.serviceName" (dict "component" "milvus" "Release" .Release) }}:19530"
        - name: MILVUS_INDEX_TYPE
          value: "HNSW"
        - name: MILVUS_METRIC_TYPE
          value: "COSINE"
        - name: MILVUS_HNSW_M
          value: "16"
        - name: MILVUS_HNSW_EFCONSTRUCTION
          value: "256"
        - name: RAG_FULL_CONTEXT
          value: "True"
        - name: RAG_EMBEDDING_BATCH_SIZE
          value: "64"
        - name: PDF_EXTRACT_IMAGES
          value: "True"
        - name: RAG_FILE_MAX_COUNT
          value: "4"
        - name: CONTENT_EXTRACTION_ENGINE
          value: "docling"
        - name: DOCLING_SERVER_URL
          value: "http://{{ include "aihub.serviceName" (dict "component" "docling" "Release" .Release) }}:5001"
        - name: DOCLING_OCR_ENGINE
          value: "easyocr"
        - name: DOCLING_OCR_LANG
          value: "en,de,fr,it"
        - name: ENABLE_WEB_SEARCH
          value: "True"
        - name: WEB_SEARCH_ENGINE
          value: "jina"
        - name: JINA_API_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" . }}-env
              key: JINA_API_KEY
        - name: WEB_SEARCH_RESULT_COUNT
          value: "6"
        - name: WEB_SEARCH_CONCURRENT_REQUESTS
          value: "6"
        - name: BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL
          value: "True"
        - name: WEB_LOADER_ENGINE
          value: "playwright"
        - name: PLAYWRIGHT_WS_URL
          value: "ws://{{ include "aihub.serviceName" (dict "component" "playwright" "Release" .Release) }}:3000"
        - name: FILE_IMAGE_COMPRESSION_WIDTH
          value: "796"
        - name: FILE_IMAGE_COMPRESSION_HEIGHT
          value: "796"
        - name: IMAGE_GENERATION_MODEL
          value: "azure/dall-e-3"
        - name: IMAGE_SIZE
          value: "1024x1024"
        - name: AUDIO_STT_ENGINE
          value: "openai"
        - name: AUDIO_TTS_ENGINE
          value: "openai"
        - name: AUDIO_STT_MODEL
          value: "azure/gpt-4o-mini-transcribe"
        - name: AUDIO_TTS_MODEL
          value: "azure/gpt-4o-mini-tts"
        - name: AUDIO_TTS_VOICE
          value: "alloy"
        - name: USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS
          value: "False"
        - name: USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ACCESS
          value: "False"
        - name: USER_PERMISSIONS_WORKSPACE_PROMPTS_ACCESS
          value: "False"
        - name: USER_PERMISSIONS_WORKSPACE_TOOLS_ACCESS
          value: "False"
        - name: USER_PERMISSIONS_WORKSPACE_MODELS_ALLOW_PUBLIC_SHARING
          value: "False"
        - name: USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ALLOW_PUBLIC_SHARING
          value: "False"
        - name: USER_PERMISSIONS_WORKSPACE_PROMPTS_ALLOW_PUBLIC_SHARING
          value: "False"
        - name: USER_PERMISSIONS_WORKSPACE_TOOLS_ALLOW_PUBLIC_SHARING
          value: "False"
        - name: USER_PERMISSIONS_CHAT_CONTROLS
          value: "True"
        - name: USER_PERMISSIONS_CHAT_SYSTEM_PROMPT
          value: "True"
        - name: USER_PERMISSIONS_CHAT_FILE_UPLOAD
          value: "True"
        - name: USER_PERMISSIONS_CHAT_DELETE
          value: "True"
        - name: USER_PERMISSIONS_CHAT_EDIT
          value: "True"
        - name: USER_PERMISSIONS_CHAT_SHARE
          value: "False"
        - name: USER_PERMISSIONS_CHAT_EXPORT
          value: "False"
        - name: USER_PERMISSIONS_CHAT_STT
          value: "True"
        - name: USER_PERMISSIONS_CHAT_TTS
          value: "True"
        - name: USER_PERMISSIONS_CHAT_CALL
          value: "True"
        - name: USER_PERMISSIONS_CHAT_MULTIPLE_MODELS
          value: "True"
        - name: USER_PERMISSIONS_CHAT_TEMPORARY
          value: "True"
        - name: USER_PERMISSIONS_CHAT_TEMPORARY_ENFORCED
          value: "False"
        - name: USER_PERMISSIONS_FEATURES_DIRECT_TOOL_SERVERS
          value: "False"
        - name: USER_PERMISSIONS_FEATURES_WEB_SEARCH
          value: "True"
        - name: USER_PERMISSIONS_FEATURES_IMAGE_GENERATION
          value: "True"
        - name: USER_PERMISSIONS_FEATURES_CODE_INTERPRETER
          value: "True"
        - name: USER_PERMISSIONS_FEATURES_NOTES
          value: "True"
        ports:
        - containerPort: 8080
          name: webui
        volumeMounts:
        {{- include "aihub.commonVolumeMounts" . | nindent 8 }}
        - name: openwebui-data
          mountPath: /app/backend/data
        resources:
          {{- toYaml .Values.openWebui.resources | nindent 10 }}
      volumes:
      {{- include "aihub.commonVolumes" . | nindent 6 }}
      - name: openwebui-data
        persistentVolumeClaim:
          claimName: {{ include "aihub.pvcName" (dict "component" "openwebui-data" "Release" .Release) }}
{{- end }}
