# This file is auto-generated from a Jinja2 template.
# DO NOT EDIT THIS FILE DIRECTLY.
#
# To make changes, edit deployment/templates/configs/init.Dockerfile.j2

# Multi-stage build to extract etcdctl from our etcd image
# This ensures architecture compatibility (AMD64/ARM64) and eliminates runtime downloads

# 1. Use our existing etcd image as the source for the binary
FROM ghcr.io/bbvch-ai/swiss-ai-hub/etcd:v3.5.25 AS source

# 2. Use Alpine to get a shell environment
FROM alpine:3.19

# 3. Copy the etcdctl binary from the source image
# This automatically matches the CPU architecture (ARM or AMD)!
COPY --from=source /usr/local/bin/etcdctl /usr/local/bin/etcdctl
COPY init_etcd.sh /usr/local/bin/init_etcd.sh

RUN chmod +x /usr/local/bin/init_etcd.sh

ENTRYPOINT ["/bin/sh", "/usr/local/bin/init_etcd.sh"]
