"""Wiring test for conversation-metadata adoption (analogous to test_self_awareness_wiring).

Conversation metadata (title + follow-up questions) is generated by the shared best-effort functions in
``conversation_metadata_step_functions``. How an agent adopts them depends on its answer event (see ADRs
2026_06_18_conversation_metadata_as_explicit_per_agent_steps and
2026_07_13_response_format_as_default_structured_output):

- **Split** (RAGAgent, ExpertRAGAgent) — the answer is a *non-terminal* ``LLMEvent`` reached only after a
  multi-step retrieval/answer pipeline. The **title** runs as an early fan-out ``@step`` anchored on an
  early, pre-answer event (it only needs the topic, not the answer) so it completes before the stop event;
  the **follow-ups** run **inline** in the terminal step (they are grounded on the answer, so cannot start
  earlier). This split is what keeps either metadata event from racing the StopEvent teardown.
- **Inline** (LLMWrappingAgent, FewShotAgent, McpReactAgent) — the answer *is* a stop event the dispatcher
  won't dispatch steps for, so both title and follow-ups are generated by the best-effort
  ``generate_conversation_metadata`` helper inside the terminal step, before the stop event is returned.

The same split/inline logic applies separately to the **meta-question branch** for the four self-aware
metadata adopters (RAGAgent, ExpertRAGAgent, FewShotAgent, LLMWrappingAgent — McpReactAgent has no
meta-question steps at all): title is always an early, parallel ``@step`` anchored on
``MetaQuestionDetectedEvent`` (the same event ``answer_meta_question_step`` triggers on, so the dispatcher
runs both concurrently), regardless of whether the agent's *normal* flow is split or inline — the meta
branch's answer is always a terminal ``LLMStopEvent`` with no separate stop step, so title generation must
not wait on it. Follow-ups are inline in ``answer_meta_question_step`` itself (they need the answer, so
there's no earlier point to generate them).

Two additional exit paths bypass their agent's normal metadata call site entirely, for the same
"dispatcher won't dispatch a step waiting on a stop event" reason: ``FewShotAgent``'s guard-reject
``stop_step`` (both, neither has fired yet) and ``ExpertRAGAgent``'s
``expert_not_answered_step``/``expert_exception_step`` (follow-ups only, title's early fan-out step
already fires regardless of branch). ``McpReactAgent``'s ``max_iterations_reached_step`` has the same
structural gap but is deliberately left without metadata — a run that never produced an answer isn't
worth titling.

This test pins the adoption set so a new conversational agent can't silently forget to adopt, the title
can't silently regress to hanging off the answer event (which raced teardown), and the excluded agents
can't silently gain metadata.
"""

import inspect

from swiss_ai_hub.agent.agents.agent import Agent
from swiss_ai_hub.agent.agents.expert_asking_agent.expert_asking_agent import ExpertAskingAgent
from swiss_ai_hub.agent.agents.expert_rag_agent.expert_rag_agent import ExpertRAGAgent
from swiss_ai_hub.agent.agents.few_shot_agent.few_shot_agent import FewShotAgent
from swiss_ai_hub.agent.agents.llm_wrapping_agent.llm_wrapping_agent import LLMWrappingAgent
from swiss_ai_hub.agent.agents.mcp_react_agent.mcp_react_agent import McpReactAgent
from swiss_ai_hub.agent.agents.namespace_selection_agent.namespace_selection_agent import NamespaceSelectionAgent
from swiss_ai_hub.agent.agents.rag_agent.rag_agent import RAGAgent
from swiss_ai_hub.agent.agents.retrieval_agent.retrieval_agent import RetrievalAgent

INLINE_HELPER = "generate_conversation_metadata"
TITLE_GENERATOR = "generate_title"
FOLLOW_UP_GENERATOR = "generate_follow_up_questions"
TITLE_STEP = "generate_conversation_title_step"
FOLLOW_UP_STEP = "generate_follow_up_questions_step"
METADATA_STEP_WRAPPERS = {TITLE_STEP, FOLLOW_UP_STEP}

META_ANSWER_STEP = "answer_meta_question_step"
META_TITLE_STEP = "generate_meta_question_title_step"

SPLIT_AGENTS = [RAGAgent, ExpertRAGAgent]
INLINE_AGENTS = [LLMWrappingAgent, FewShotAgent, McpReactAgent]

# Self-aware agents that also adopt conversation metadata — every self-aware agent today, minus
# McpReactAgent (not self-aware at all, so it has no meta-question branch to wire metadata into).
META_QUESTION_METADATA_AGENTS = [RAGAgent, ExpertRAGAgent, FewShotAgent, LLMWrappingAgent]

# Non-answer-owning or non-conversational agents that must never generate conversation metadata.
EXCLUDED_AGENTS = [RetrievalAgent, NamespaceSelectionAgent, ExpertAskingAgent]


def _step_names(agent_type) -> set[str]:
    return {step.__name__ for step in agent_type.get_steps()}


def _step_by_name(agent_type, name: str):
    return next(step for step in agent_type.get_steps() if step.__name__ == name)


def _input_event_names(step) -> set[str]:
    return {event_class.__name__ for event_class in getattr(step, Agent.INPUT_EVENTS_ANNOTATION, set())}


def _step_source(agent_type, step_name: str) -> str:
    return inspect.getsource(_step_by_name(agent_type, step_name))


def test_split_agents_title_is_early_fan_out_and_follow_ups_are_inline():
    for agent_type in SPLIT_AGENTS:
        source = inspect.getsource(agent_type)
        step_names = _step_names(agent_type)

        # Title: an explicit early fan-out @step delegating to the best-effort generator.
        assert TITLE_STEP in step_names, f"{agent_type.__name__} must define the {TITLE_STEP} @step"
        assert TITLE_GENERATOR in source, f"{agent_type.__name__} must call {TITLE_GENERATOR}"

        # The title must NOT hang off the answer event: that is exactly what raced the StopEvent teardown
        # (dropped/reordered title). It only needs the topic, so it anchors on an early, pre-answer event.
        title_inputs = _input_event_names(_step_by_name(agent_type, TITLE_STEP))
        assert "LLMEvent" not in title_inputs, (
            f"{agent_type.__name__}.{TITLE_STEP} must not consume LLMEvent — the title must be generated "
            "early (pre-answer) so it never races the stop-event teardown"
        )

        # Follow-ups: inline (grounded on the answer), never a fan-out @step.
        assert FOLLOW_UP_GENERATOR in source, f"{agent_type.__name__} must call {FOLLOW_UP_GENERATOR} inline"
        assert FOLLOW_UP_STEP not in step_names, (
            f"{agent_type.__name__} must generate follow-ups inline before the stop event, not as a fan-out "
            "@step (a fan-out follow-up step races the stop-event teardown)"
        )


def test_inline_agents_call_helper_without_step_wrappers():
    for agent_type in INLINE_AGENTS:
        assert INLINE_HELPER in inspect.getsource(agent_type), f"{agent_type.__name__} must call {INLINE_HELPER} inline"
        assert not (METADATA_STEP_WRAPPERS & _step_names(agent_type)), (
            f"{agent_type.__name__} adopts inline and must not define metadata @step wrappers"
        )


def test_excluded_agents_have_no_conversation_metadata():
    for agent_type in EXCLUDED_AGENTS:
        source = inspect.getsource(agent_type)
        assert INLINE_HELPER not in source
        assert TITLE_GENERATOR not in source, f"{agent_type.__name__} must not call {TITLE_GENERATOR}"
        assert FOLLOW_UP_GENERATOR not in source, f"{agent_type.__name__} must not call {FOLLOW_UP_GENERATOR}"
        assert not (METADATA_STEP_WRAPPERS & _step_names(agent_type))


def test_meta_question_branch_has_an_early_parallel_title_step():
    """Title must not wait on the meta answer — it only needs the user's question, and waiting would add
    post-answer latency (the answer is already fully streamed by the time the answer step returns, but
    the stop event — and the client's "generation done" signal — would still be held back)."""
    for agent_type in META_QUESTION_METADATA_AGENTS:
        step_names = _step_names(agent_type)
        assert META_TITLE_STEP in step_names, f"{agent_type.__name__} must define the {META_TITLE_STEP} @step"

        title_step = _step_by_name(agent_type, META_TITLE_STEP)
        assert TITLE_GENERATOR in inspect.getsource(title_step), (
            f"{agent_type.__name__}.{META_TITLE_STEP} must call {TITLE_GENERATOR}"
        )

        title_inputs = _input_event_names(title_step)
        assert "MetaQuestionDetectedEvent" in title_inputs, (
            f"{agent_type.__name__}.{META_TITLE_STEP} must trigger on MetaQuestionDetectedEvent — the "
            "same event answer_meta_question_step triggers on, so the dispatcher runs both concurrently"
        )
        assert "LLMStopEvent" not in title_inputs, (
            f"{agent_type.__name__}.{META_TITLE_STEP} must not wait on the meta answer's LLMStopEvent"
        )


def test_meta_question_answer_step_generates_follow_ups_only():
    """Follow-ups need the answer, so they're stuck inline in answer_meta_question_step — but title must
    NOT also be called there (it belongs to the parallel step above; calling it here would serialize it
    behind the answer for no reason)."""
    for agent_type in META_QUESTION_METADATA_AGENTS:
        source = _step_source(agent_type, META_ANSWER_STEP)
        assert FOLLOW_UP_GENERATOR in source, (
            f"{agent_type.__name__}.{META_ANSWER_STEP} must call {FOLLOW_UP_GENERATOR}"
        )
        assert TITLE_GENERATOR not in source, (
            f"{agent_type.__name__}.{META_ANSWER_STEP} must not call {TITLE_GENERATOR} — title runs in "
            f"parallel via {META_TITLE_STEP}, not serialized behind the answer"
        )
        assert INLINE_HELPER not in source, (
            f"{agent_type.__name__}.{META_ANSWER_STEP} must not call the bundled {INLINE_HELPER} helper "
            f"(it would also generate the title, redundantly and too late) — call {FOLLOW_UP_GENERATOR} alone"
        )


def test_mcp_react_agent_has_no_meta_question_branch():
    """McpReactAgent isn't self-aware, so it has no meta-question flow to wire metadata into."""
    assert META_ANSWER_STEP not in _step_names(McpReactAgent)
    assert META_TITLE_STEP not in _step_names(McpReactAgent)


def test_expert_rag_agent_decline_and_error_paths_generate_follow_ups():
    """Title already fires early (fan-out step, unaffected by this branching); only follow-ups are
    missing on the expert-decline/expert-error exit paths, grounded on the canned decline/error message
    as the "answer" — same treatment as ExpertRAGAgent's other canned-message exit paths."""
    for step_name in ("expert_not_answered_step", "expert_exception_step"):
        source = _step_source(ExpertRAGAgent, step_name)
        assert FOLLOW_UP_GENERATOR in source, f"ExpertRAGAgent.{step_name} must call {FOLLOW_UP_GENERATOR}"
        assert TITLE_GENERATOR not in source, (
            f"ExpertRAGAgent.{step_name} must not call {TITLE_GENERATOR} — the early fan-out step "
            "already covers title for this run regardless of which branch is taken"
        )


def test_few_shot_agent_guard_reject_generates_title_and_follow_ups():
    """Neither title nor follow-ups have fired yet when the suitability guard rejects the request, so
    both are needed here — unlike ExpertRAGAgent's decline/error paths, which already have an early title
    step."""
    source = _step_source(FewShotAgent, "stop_step")
    assert INLINE_HELPER in source, f"FewShotAgent.stop_step (guard-reject) must call {INLINE_HELPER}"


def test_mcp_react_agent_max_iterations_generates_no_metadata():
    """No metadata on this path, by product decision — not worth titling a run that never answered."""
    source = _step_source(McpReactAgent, "max_iterations_reached_step")
    assert TITLE_GENERATOR not in source, "McpReactAgent.max_iterations_reached_step must not call generate_title"
    assert FOLLOW_UP_GENERATOR not in source, (
        "McpReactAgent.max_iterations_reached_step must not call generate_follow_up_questions"
    )
    assert INLINE_HELPER not in source, (
        "McpReactAgent.max_iterations_reached_step must not call generate_conversation_metadata"
    )
