"""Wiring test for conversation-metadata adoption (analogous to test_self_awareness_wiring).

Conversation metadata (title + follow-up questions) is generated by the shared best-effort functions in
``conversation_metadata_step_functions``. How an agent adopts them depends on its answer event (see ADRs
2026_06_18_conversation_metadata_as_explicit_per_agent_steps and
2026_07_13_response_format_as_default_structured_output):

- **Split** (RAGAgent, ExpertRAGAgent) — the answer is a *non-terminal* ``LLMEvent`` reached only after a
  multi-step retrieval/answer pipeline. The **title** runs as an early fan-out ``@step`` anchored on an
  early, pre-answer event (it only needs the topic, not the answer) so it completes before the stop event;
  the **follow-ups** run **inline** in the terminal step (they are grounded on the answer, so cannot start
  earlier). This split is what keeps either metadata event from racing the StopEvent teardown.
- **Inline** (LLMWrappingAgent, FewShotAgent, McpReactAgent) — the answer *is* a stop event the dispatcher
  won't dispatch steps for, so both title and follow-ups are generated by the best-effort
  ``generate_conversation_metadata`` helper inside the terminal step, before the stop event is returned.

This test pins the adoption set so a new conversational agent can't silently forget to adopt, the title
can't silently regress to hanging off the answer event (which raced teardown), and the excluded agents
can't silently gain metadata.
"""

import inspect

from swiss_ai_hub.agent.agents.agent import Agent
from swiss_ai_hub.agent.agents.expert_asking_agent.expert_asking_agent import ExpertAskingAgent
from swiss_ai_hub.agent.agents.expert_rag_agent.expert_rag_agent import ExpertRAGAgent
from swiss_ai_hub.agent.agents.few_shot_agent.few_shot_agent import FewShotAgent
from swiss_ai_hub.agent.agents.llm_wrapping_agent.llm_wrapping_agent import LLMWrappingAgent
from swiss_ai_hub.agent.agents.mcp_react_agent.mcp_react_agent import McpReactAgent
from swiss_ai_hub.agent.agents.namespace_selection_agent.namespace_selection_agent import NamespaceSelectionAgent
from swiss_ai_hub.agent.agents.rag_agent.rag_agent import RAGAgent
from swiss_ai_hub.agent.agents.retrieval_agent.retrieval_agent import RetrievalAgent

INLINE_HELPER = "generate_conversation_metadata"
TITLE_GENERATOR = "generate_title"
FOLLOW_UP_GENERATOR = "generate_follow_up_questions"
TITLE_STEP = "generate_conversation_title_step"
FOLLOW_UP_STEP = "generate_follow_up_questions_step"
METADATA_STEP_WRAPPERS = {TITLE_STEP, FOLLOW_UP_STEP}

SPLIT_AGENTS = [RAGAgent, ExpertRAGAgent]
INLINE_AGENTS = [LLMWrappingAgent, FewShotAgent, McpReactAgent]

# Non-answer-owning or non-conversational agents that must never generate conversation metadata.
EXCLUDED_AGENTS = [RetrievalAgent, NamespaceSelectionAgent, ExpertAskingAgent]


def _step_names(agent_type) -> set[str]:
    return {step.__name__ for step in agent_type.get_steps()}


def _step_by_name(agent_type, name: str):
    return next(step for step in agent_type.get_steps() if step.__name__ == name)


def _input_event_names(step) -> set[str]:
    return {event_class.__name__ for event_class in getattr(step, Agent.INPUT_EVENTS_ANNOTATION, set())}


def test_split_agents_title_is_early_fan_out_and_follow_ups_are_inline():
    for agent_type in SPLIT_AGENTS:
        source = inspect.getsource(agent_type)
        step_names = _step_names(agent_type)

        # Title: an explicit early fan-out @step delegating to the best-effort generator.
        assert TITLE_STEP in step_names, f"{agent_type.__name__} must define the {TITLE_STEP} @step"
        assert TITLE_GENERATOR in source, f"{agent_type.__name__} must call {TITLE_GENERATOR}"

        # The title must NOT hang off the answer event: that is exactly what raced the StopEvent teardown
        # (dropped/reordered title). It only needs the topic, so it anchors on an early, pre-answer event.
        title_inputs = _input_event_names(_step_by_name(agent_type, TITLE_STEP))
        assert "LLMEvent" not in title_inputs, (
            f"{agent_type.__name__}.{TITLE_STEP} must not consume LLMEvent — the title must be generated "
            "early (pre-answer) so it never races the stop-event teardown"
        )

        # Follow-ups: inline (grounded on the answer), never a fan-out @step.
        assert FOLLOW_UP_GENERATOR in source, f"{agent_type.__name__} must call {FOLLOW_UP_GENERATOR} inline"
        assert FOLLOW_UP_STEP not in step_names, (
            f"{agent_type.__name__} must generate follow-ups inline before the stop event, not as a fan-out "
            "@step (a fan-out follow-up step races the stop-event teardown)"
        )


def test_inline_agents_call_helper_without_step_wrappers():
    for agent_type in INLINE_AGENTS:
        assert INLINE_HELPER in inspect.getsource(agent_type), f"{agent_type.__name__} must call {INLINE_HELPER} inline"
        assert not (METADATA_STEP_WRAPPERS & _step_names(agent_type)), (
            f"{agent_type.__name__} adopts inline and must not define metadata @step wrappers"
        )


def test_excluded_agents_have_no_conversation_metadata():
    for agent_type in EXCLUDED_AGENTS:
        source = inspect.getsource(agent_type)
        assert INLINE_HELPER not in source
        assert TITLE_GENERATOR not in source and FOLLOW_UP_GENERATOR not in source, (
            f"{agent_type.__name__} must not generate conversation metadata"
        )
        assert not (METADATA_STEP_WRAPPERS & _step_names(agent_type))
