"""Wiring test for conversation-metadata adoption (analogous to test_self_awareness_wiring).

Conversation metadata (title + follow-up questions) is generated by the shared free functions
``do_generate_title`` / ``do_generate_follow_up_questions``. Agents adopt them in one of two shapes
(see ADR 2026_06_18_conversation_metadata_as_explicit_per_agent_steps):

- **Fan-out @step wrappers** — for agents whose answer is a *non-terminal* ``LLMEvent`` the steps can
  hook on (RAGAgent, ExpertRAGAgent).
- **Inline in the terminal step** — for agents whose answer is a *stop event* the dispatcher won't
  dispatch steps for, so the generators are awaited inline before returning the stop event
  (LLMWrappingAgent, FewShotAgent, McpReactAgent).

This test pins the adoption set so a new conversational agent can't silently forget to adopt, and the
excluded agents can't silently gain it.
"""

import inspect

from swiss_ai_hub.agent.agents.expert_asking_agent.expert_asking_agent import ExpertAskingAgent
from swiss_ai_hub.agent.agents.expert_rag_agent.expert_rag_agent import ExpertRAGAgent
from swiss_ai_hub.agent.agents.few_shot_agent.few_shot_agent import FewShotAgent
from swiss_ai_hub.agent.agents.llm_wrapping_agent.llm_wrapping_agent import LLMWrappingAgent
from swiss_ai_hub.agent.agents.mcp_react_agent.mcp_react_agent import McpReactAgent
from swiss_ai_hub.agent.agents.namespace_selection_agent.namespace_selection_agent import NamespaceSelectionAgent
from swiss_ai_hub.agent.agents.rag_agent.rag_agent import RAGAgent
from swiss_ai_hub.agent.agents.retrieval_agent.retrieval_agent import RetrievalAgent

GENERATORS = ("do_generate_title", "do_generate_follow_up_questions")
STEP_WRAPPERS = {"generate_conversation_title_step", "generate_follow_up_questions_step"}

# Every answer-owning conversational agent generates both metadata types (via fan-out or inline).
ADOPTING_AGENTS = [RAGAgent, ExpertRAGAgent, LLMWrappingAgent, FewShotAgent, McpReactAgent]

# Of those, the ones whose answer is a non-terminal LLMEvent adopt via dedicated @step wrappers.
STEP_BASED_AGENTS = [RAGAgent, ExpertRAGAgent]

# Non-answer-owning or non-conversational agents that must never generate conversation metadata.
EXCLUDED_AGENTS = [RetrievalAgent, NamespaceSelectionAgent, ExpertAskingAgent]


def _step_names(agent_type) -> set[str]:
    return {step.__name__ for step in agent_type.get_steps()}


def test_adopting_agents_invoke_both_generators():
    for agent_type in ADOPTING_AGENTS:
        source = inspect.getsource(agent_type)
        for generator in GENERATORS:
            assert generator in source, f"{agent_type.__name__} must invoke {generator}"


def test_step_based_agents_define_both_step_wrappers():
    for agent_type in STEP_BASED_AGENTS:
        assert STEP_WRAPPERS.issubset(_step_names(agent_type)), (
            f"{agent_type.__name__} must define both conversation-metadata @step wrappers"
        )


def test_inline_agents_do_not_define_step_wrappers():
    """Inline adopters must not also declare the steps (would double-emit / never dispatch)."""
    for agent_type in [LLMWrappingAgent, FewShotAgent, McpReactAgent]:
        assert not (STEP_WRAPPERS & _step_names(agent_type)), (
            f"{agent_type.__name__} adopts inline and must not define metadata @step wrappers"
        )


def test_excluded_agents_have_no_conversation_metadata():
    for agent_type in EXCLUDED_AGENTS:
        source = inspect.getsource(agent_type)
        assert not any(generator in source for generator in GENERATORS), (
            f"{agent_type.__name__} must not generate conversation metadata"
        )
        assert not (STEP_WRAPPERS & _step_names(agent_type))
