// This file is auto-generated by @hey-api/openapi-ts

export const AccessSchema = {
  properties: {
    services: {
      items: {
        $ref: "#/components/schemas/UserAccess",
      },
      type: "array",
      title: "Services",
      description: "List of services and access levels",
      default: [],
    },
    agents: {
      items: {
        $ref: "#/components/schemas/UserAccess",
      },
      type: "array",
      title: "Agents",
      description: "List of agents and access levels",
      default: [],
    },
    processes: {
      items: {
        $ref: "#/components/schemas/UserAccess",
      },
      type: "array",
      title: "Processes",
      description: "List of processes and access levels",
      default: [],
    },
  },
  type: "object",
  title: "Access",
} as const;

export const AccessLevelSchema = {
  type: "integer",
  enum: [0, 1, 2],
  title: "AccessLevel",
  description: "Defines the possible outcomes of a permission check.",
} as const;

export const AgentHealthChecksSchema = {
  properties: {
    running: {
      type: "boolean",
      title: "Running",
      description: "Whether the agent runner is running.",
    },
    nats: {
      type: "boolean",
      title: "Nats",
      description: "NATS message broker connectivity.",
    },
    redis: {
      type: "boolean",
      title: "Redis",
      description: "Redis/Valkey cache connectivity.",
    },
    milvus: {
      type: "boolean",
      title: "Milvus",
      description: "Milvus vector database connectivity.",
    },
  },
  type: "object",
  required: ["running", "nats", "redis", "milvus"],
  title: "AgentHealthChecks",
  description: "Health check results for Agent service dependencies.",
} as const;

export const ApiHealthChecksSchema = {
  properties: {
    nats: {
      type: "boolean",
      title: "Nats",
      description: "NATS message broker connectivity.",
    },
    mongodb: {
      type: "boolean",
      title: "Mongodb",
      description: "MongoDB database connectivity.",
    },
    redis: {
      type: "boolean",
      title: "Redis",
      description: "Redis/Valkey cache connectivity.",
    },
    milvus: {
      type: "boolean",
      title: "Milvus",
      description: "Milvus vector database connectivity.",
    },
    s3: {
      type: "boolean",
      title: "S3",
      description: "S3/SeaweedFS object storage connectivity.",
    },
  },
  type: "object",
  required: ["nats", "mongodb", "redis", "milvus", "s3"],
  title: "ApiHealthChecks",
  description: "Health check results for API service dependencies.",
} as const;

export const AuthProviderResponseSchema = {
  properties: {
    alias: {
      type: "string",
      title: "Alias",
      description: "Keycloak IDP alias used as kc_idp_hint parameter",
    },
    display_name: {
      type: "string",
      title: "Display Name",
      description: "Human-readable name for the login button",
    },
    icon: {
      type: "string",
      title: "Icon",
      description: "PrimeIcon CSS class (e.g., pi-microsoft, pi-lock)",
    },
  },
  type: "object",
  required: ["alias", "display_name", "icon"],
  title: "AuthProviderResponse",
  description: "Represents a single identity provider available for login.",
} as const;

export const CreateRoleRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "The unique name of the role.",
    },
    description: {
      type: "string",
      title: "Description",
      description: "A short description of the role's purpose.",
    },
    access_rules: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Access Rules",
      description: "A list of access rules granted by this role.",
      default: [],
    },
    usage_limits: {
      items: {
        $ref: "#/components/schemas/UsageLimitDTO",
      },
      type: "array",
      title: "Usage Limits",
      description: "Pattern-based usage limit rules.",
      default: [],
    },
  },
  type: "object",
  required: ["name", "description"],
  title: "CreateRoleRequest",
  description: "Request model for creating a new role.",
} as const;

export const CreateTenantMetadataRequestSchema = {
  properties: {
    tenant_id: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Tenant Id",
      description:
        "Keycloak tenant group name (must already exist under /tenants/).",
    },
    name: {
      type: "string",
      maxLength: 120,
      minLength: 1,
      title: "Name",
      description: "The unique display name of the tenant.",
    },
    description: {
      type: "string",
      maxLength: 500,
      title: "Description",
      description: "A short description of the tenant.",
      default: "",
    },
    access_rules: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Access Rules",
      description: "Access rules granted to this tenant.",
      default: [],
    },
  },
  type: "object",
  required: ["tenant_id", "name"],
  title: "CreateTenantMetadataRequest",
  description:
    "Request model for attaching metadata to an existing Keycloak tenant group.\n\n``tenant_id`` is not user-chosen here — it must already exist as a Keycloak group\nunder ``/tenants/``. Use the ``/admin/tenants/unconfigured`` endpoint to list\nconfigurable ids. A regex constraint is deliberately avoided because Keycloak\naccepts group names this layer would otherwise reject (e.g. ``MyTenant``,\n``customer.acme``); the only checks that belong here are a minimum length (reject\nempty payloads) and a maximum length matching Keycloak's group-name cap (DoS guard\nagainst unbounded strings reaching Mongo).",
} as const;

export const DashboardDTOSchema = {
  properties: {
    minRow: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Minrow",
      description: "Minimum number of rows in the grid.",
    },
    margin: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Margin",
      description: "Gap between grid items in pixels.",
    },
    column: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Column",
      description: "Number of columns in the grid.",
    },
    cellHeight: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Cellheight",
      description: "Height of one cell in pixels.",
    },
    children: {
      items: {
        $ref: "#/components/schemas/DashboardItemDTO",
      },
      type: "array",
      title: "Children",
      description: "List of widgets (dashboard items) within the grid.",
      default: [],
    },
  },
  type: "object",
  title: "DashboardDTO",
} as const;

export const DashboardItemDTOSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the dashboard widget.",
    },
    component: {
      type: "string",
      title: "Component",
      description: "Specifies the component to render for this widget.",
    },
    x: {
      type: "integer",
      title: "X",
      description: "The x-coordinate of the widget in the grid.",
    },
    y: {
      type: "integer",
      title: "Y",
      description: "The y-coordinate of the widget in the grid.",
    },
    w: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "W",
      description: "Width of the widget in grid column units.",
    },
    noResize: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Noresize",
      description: "If true, the widget cannot be resized.",
    },
    timeRange: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Timerange",
      description: "Time range for the data displayed in the widget.",
    },
    event: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Event",
      description: "The type of event data the widget displays.",
    },
  },
  type: "object",
  required: ["id", "component", "x", "y"],
  title: "DashboardItemDTO",
} as const;

export const DeleteRoleResponseSchema = {
  properties: {
    detail: {
      type: "string",
      title: "Detail",
      description: "A confirmation message for the deletion.",
      default: "Role deleted successfully.",
    },
  },
  type: "object",
  title: "DeleteRoleResponse",
  description: "Confirmation response for a successful deletion.",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
      description: "The health status of the application.",
    },
    code: {
      type: "integer",
      title: "Code",
      description: "HTTP status code.",
    },
    checks: {
      anyOf: [
        {
          $ref: "#/components/schemas/ApiHealthChecks",
        },
        {
          $ref: "#/components/schemas/AgentHealthChecks",
        },
        {
          $ref: "#/components/schemas/ProcessHealthChecks",
        },
        {
          type: "null",
        },
      ],
      title: "Checks",
      description: "Individual health check results.",
    },
  },
  type: "object",
  required: ["status", "code"],
  title: "HealthResponse",
  description: "Standard health check response.",
} as const;

export const PaginatedUsersResponseSchema = {
  properties: {
    total: {
      type: "integer",
      title: "Total",
      description: "Total number of items available",
    },
    page: {
      type: "integer",
      title: "Page",
      description: "Current page number (1-indexed)",
    },
    page_size: {
      type: "integer",
      title: "Page Size",
      description: "Number of threads per page",
    },
    total_pages: {
      type: "integer",
      title: "Total Pages",
      description: "Total number of pages available",
    },
    users: {
      items: {
        $ref: "#/components/schemas/UserDTO",
      },
      type: "array",
      title: "Users",
      description: "List of MinimalUserDTO objects for the current page.",
    },
  },
  type: "object",
  required: ["total", "page", "page_size", "total_pages", "users"],
  title: "PaginatedUsersResponse",
  description: "Represents a paginated response containing a list of users.",
} as const;

export const ProcessHealthChecksSchema = {
  properties: {
    running: {
      type: "boolean",
      title: "Running",
      description: "Whether the process runner is running.",
    },
    nats: {
      type: "boolean",
      title: "Nats",
      description: "NATS message broker connectivity.",
    },
    redis: {
      type: "boolean",
      title: "Redis",
      description: "Redis/Valkey cache connectivity.",
    },
  },
  type: "object",
  required: ["running", "nats", "redis"],
  title: "ProcessHealthChecks",
  description: "Health check results for Process service dependencies.",
} as const;

export const RoleResponseSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "The unique identifier of the role.",
    },
    name: {
      type: "string",
      title: "Name",
      description: "The name of the role.",
    },
    description: {
      type: "string",
      title: "Description",
      description: "The description of the role.",
    },
    access_rules: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Access Rules",
      description: "The list of access rules for the role.",
    },
    usage_limits: {
      items: {
        $ref: "#/components/schemas/UsageLimitDTO",
      },
      type: "array",
      title: "Usage Limits",
      description: "Pattern-based usage limit rules.",
      default: [],
    },
    tenant_id: {
      type: "string",
      title: "Tenant Id",
      description: "Tenant ID this role belongs to.",
    },
  },
  type: "object",
  required: ["id", "name", "description", "access_rules", "tenant_id"],
  title: "RoleResponse",
  description: "Response model representing a role.",
} as const;

export const TenantResponseSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description:
        "Unique tenant identifier (matches the Keycloak group name).",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Tenant display name.",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Tenant description.",
    },
    access_rules: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Access Rules",
      description: "Access rules granted to this tenant.",
    },
    state: {
      $ref: "#/components/schemas/TenantState",
      description:
        "Whether the tenant also exists in Keycloak (active) or not (orphaned).",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Tenant creation timestamp.",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
      description: "Tenant last update timestamp.",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "description",
    "access_rules",
    "state",
    "created_at",
    "updated_at",
  ],
  title: "TenantResponse",
  description: "Response model for a tenant, as seen by sysadmins.",
} as const;

export const TenantStateSchema = {
  type: "string",
  enum: ["active", "orphaned"],
  title: "TenantState",
  description:
    "Visibility state of a tenant for the sysadmin view.\n\n- ACTIVE: exists both in Keycloak (as a group) and in MongoDB (as metadata).\n- ORPHANED: exists only in MongoDB; the Keycloak group is missing. Users cannot\n  reach this tenant. Shown to sysadmins read-only with a delete action only.\n\nUnconfigured tenants (Keycloak group only, no metadata) deliberately do not\nappear here: they carry no MongoDB fields (name/description/access_rules) to\nwrap in a ``TenantResponse``, so they are served separately as ``list[str]``\nby ``/admin/tenants/unconfigured``. Promoting one to Active via\n``create_tenant_metadata`` is what introduces the metadata row that makes a\n``TenantState`` value meaningful.",
} as const;

export const UpdateRoleRequestSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
      description: "The new unique name of the role.",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "The new description for the role.",
    },
    access_rules: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Access Rules",
      description: "The new list of access rules.",
    },
    usage_limits: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/UsageLimitDTO",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Usage Limits",
      description: "Pattern-based usage limit rules.",
    },
  },
  type: "object",
  title: "UpdateRoleRequest",
  description:
    "Request model for updating an existing role. All fields are optional.",
} as const;

export const UpdateTenantMetadataRequestSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 120,
          minLength: 1,
          description: "The unique display name of the tenant.",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 500,
          description: "A short description of the tenant.",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    access_rules: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Access Rules",
      description: "Access rules granted to this tenant.",
    },
  },
  type: "object",
  title: "UpdateTenantMetadataRequest",
  description:
    "Request model for updating a tenant. All fields are optional.\n\nName and description constraints mirror ``CreateTenantMetadataRequest`` — an update\nmust not be able to slip a value past a constraint that create enforced.",
} as const;

export const UsageLimitDTOSchema = {
  properties: {
    pattern: {
      type: "string",
      title: "Pattern",
      description:
        "Full dotted resource pattern with wildcards (e.g. 'aihub.user.agent.>', 'aihub.user.process.MyProcess.*'). ",
    },
    limit: {
      type: "integer",
      minimum: 1,
      title: "Limit",
      description: "Max calls per period for this pattern.",
    },
    period: {
      $ref: "#/components/schemas/UsageLimitPeriod",
      description: "Period for limit: 1h, 1d, 7d, 1mo.",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Human-readable description of the pattern.",
    },
  },
  type: "object",
  required: ["pattern", "limit", "period"],
  title: "UsageLimitDTO",
  description: "Pattern-based usage limit rule.",
} as const;

export const UsageLimitPeriodSchema = {
  type: "string",
  enum: ["1h", "1d", "7d", "1mo"],
  title: "UsageLimitPeriod",
  description: "Supported usage limit periods.",
} as const;

export const UserAccessSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description:
        "Name of the service/agent/process to which user has access to",
    },
    level: {
      $ref: "#/components/schemas/AccessLevel",
      description: "Users access level to service/agent/process",
    },
  },
  type: "object",
  required: ["name", "level"],
  title: "UserAccess",
} as const;

export const UserDTOSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "The user's unique identifier (OID).",
    },
    name: {
      type: "string",
      title: "Name",
      description: "The user's name.",
    },
    email: {
      type: "string",
      title: "Email",
      description: "The user's email address.",
    },
    profile_image: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Profile Image",
      description: "User's profile image in base64.",
    },
    dashboard: {
      anyOf: [
        {
          $ref: "#/components/schemas/DashboardDTO",
        },
        {
          type: "null",
        },
      ],
      description: "User dashboard configuration for index page",
    },
    roles: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Roles",
      description: "Roles the user holds in the current tenant.",
      default: [],
    },
    is_sys_admin: {
      type: "boolean",
      title: "Is Sys Admin",
      description:
        "Whether the user has the AIHubSysAdmin realm role in Keycloak.",
      default: false,
    },
  },
  type: "object",
  required: ["id", "name", "email"],
  title: "UserDTO",
} as const;

export const UserWithAccessDTOSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "The user's unique identifier (OID).",
    },
    name: {
      type: "string",
      title: "Name",
      description: "The user's name.",
    },
    email: {
      type: "string",
      title: "Email",
      description: "The user's email address.",
    },
    profile_image: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Profile Image",
      description: "User's profile image in base64.",
    },
    dashboard: {
      anyOf: [
        {
          $ref: "#/components/schemas/DashboardDTO",
        },
        {
          type: "null",
        },
      ],
      description: "User dashboard configuration for index page",
    },
    roles: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Roles",
      description: "Roles the user holds in the current tenant.",
      default: [],
    },
    is_sys_admin: {
      type: "boolean",
      title: "Is Sys Admin",
      description:
        "Whether the user has the AIHubSysAdmin realm role in Keycloak.",
      default: false,
    },
    access: {
      $ref: "#/components/schemas/Access",
      description: "User access levels",
    },
  },
  type: "object",
  required: ["id", "name", "email", "access"],
  title: "UserWithAccessDTO",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
