// This file is auto-generated by @hey-api/openapi-ts

export const AgentHealthChecksSchema = {
  properties: {
    running: {
      type: "boolean",
      title: "Running",
      description: "Whether the agent runner is running.",
    },
    nats: {
      type: "boolean",
      title: "Nats",
      description: "NATS message broker connectivity.",
    },
    redis: {
      type: "boolean",
      title: "Redis",
      description: "Redis/Valkey cache connectivity.",
    },
    milvus: {
      type: "boolean",
      title: "Milvus",
      description: "Milvus vector database connectivity.",
    },
  },
  type: "object",
  required: ["running", "nats", "redis", "milvus"],
  title: "AgentHealthChecks",
  description: "Health check results for Agent service dependencies.",
} as const;

export const ApiHealthChecksSchema = {
  properties: {
    nats: {
      type: "boolean",
      title: "Nats",
      description: "NATS message broker connectivity.",
    },
    mongodb: {
      type: "boolean",
      title: "Mongodb",
      description: "MongoDB database connectivity.",
    },
    redis: {
      type: "boolean",
      title: "Redis",
      description: "Redis/Valkey cache connectivity.",
    },
    milvus: {
      type: "boolean",
      title: "Milvus",
      description: "Milvus vector database connectivity.",
    },
    s3: {
      type: "boolean",
      title: "S3",
      description: "S3/SeaweedFS object storage connectivity.",
    },
  },
  type: "object",
  required: ["nats", "mongodb", "redis", "milvus", "s3"],
  title: "ApiHealthChecks",
  description: "Health check results for API service dependencies.",
} as const;

export const CreateTenantMetadataRequestSchema = {
  properties: {
    tenant_id: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Tenant Id",
      description:
        "Keycloak tenant group name (must already exist under /tenants/).",
    },
    name: {
      type: "string",
      maxLength: 120,
      minLength: 1,
      title: "Name",
      description: "The unique display name of the tenant.",
    },
    description: {
      type: "string",
      maxLength: 500,
      title: "Description",
      description: "A short description of the tenant.",
      default: "",
    },
    access_rules: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Access Rules",
      description: "Access rules granted to this tenant.",
      default: [],
    },
  },
  type: "object",
  required: ["tenant_id", "name"],
  title: "CreateTenantMetadataRequest",
  description:
    "Request model for attaching metadata to an existing Keycloak tenant group.\n\n``tenant_id`` is not user-chosen here — it must already exist as a Keycloak group\nunder ``/tenants/``. Use the ``/admin/tenants/unconfigured`` endpoint to list\nconfigurable ids. A regex constraint is deliberately avoided because Keycloak\naccepts group names this layer would otherwise reject (e.g. ``MyTenant``,\n``customer.acme``); the only checks that belong here are a minimum length (reject\nempty payloads) and a maximum length matching Keycloak's group-name cap (DoS guard\nagainst unbounded strings reaching Mongo).",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
      description: "The health status of the application.",
    },
    code: {
      type: "integer",
      title: "Code",
      description: "HTTP status code.",
    },
    checks: {
      anyOf: [
        {
          $ref: "#/components/schemas/ApiHealthChecks",
        },
        {
          $ref: "#/components/schemas/AgentHealthChecks",
        },
        {
          $ref: "#/components/schemas/ProcessHealthChecks",
        },
        {
          type: "null",
        },
      ],
      title: "Checks",
      description: "Individual health check results.",
    },
  },
  type: "object",
  required: ["status", "code"],
  title: "HealthResponse",
  description: "Standard health check response.",
} as const;

export const ProcessHealthChecksSchema = {
  properties: {
    running: {
      type: "boolean",
      title: "Running",
      description: "Whether the process runner is running.",
    },
    nats: {
      type: "boolean",
      title: "Nats",
      description: "NATS message broker connectivity.",
    },
    redis: {
      type: "boolean",
      title: "Redis",
      description: "Redis/Valkey cache connectivity.",
    },
  },
  type: "object",
  required: ["running", "nats", "redis"],
  title: "ProcessHealthChecks",
  description: "Health check results for Process service dependencies.",
} as const;

export const TenantResponseSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description:
        "Unique tenant identifier (matches the Keycloak group name).",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Tenant display name.",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Tenant description.",
    },
    access_rules: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Access Rules",
      description: "Access rules granted to this tenant.",
    },
    state: {
      $ref: "#/components/schemas/TenantState",
      description:
        "Whether the tenant also exists in Keycloak (active) or not (orphaned).",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Tenant creation timestamp.",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
      description: "Tenant last update timestamp.",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "description",
    "access_rules",
    "state",
    "created_at",
    "updated_at",
  ],
  title: "TenantResponse",
  description: "Response model for a tenant, as seen by sysadmins.",
} as const;

export const TenantStateSchema = {
  type: "string",
  enum: ["active", "orphaned"],
  title: "TenantState",
  description:
    "Visibility state of a tenant for the sysadmin view.\n\n- ACTIVE: exists both in Keycloak (as a group) and in MongoDB (as metadata).\n- ORPHANED: exists only in MongoDB; the Keycloak group is missing. Users cannot\n  reach this tenant. Shown to sysadmins read-only with a delete action only.\n\nUnconfigured tenants (Keycloak group only, no metadata) deliberately do not\nappear here: they carry no MongoDB fields (name/description/access_rules) to\nwrap in a ``TenantResponse``, so they are served separately as ``list[str]``\nby ``/admin/tenants/unconfigured``. Promoting one to Active via\n``create_tenant_metadata`` is what introduces the metadata row that makes a\n``TenantState`` value meaningful.",
} as const;

export const UpdateTenantMetadataRequestSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 120,
          minLength: 1,
          description: "The unique display name of the tenant.",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 500,
          description: "A short description of the tenant.",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    access_rules: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Access Rules",
      description: "Access rules granted to this tenant.",
    },
  },
  type: "object",
  title: "UpdateTenantMetadataRequest",
  description:
    "Request model for updating a tenant. All fields are optional.\n\nName and description constraints mirror ``CreateTenantMetadataRequest`` — an update\nmust not be able to slip a value past a constraint that create enforced.",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const WhoamiResponseSchema = {
  properties: {
    is_sys_admin: {
      type: "boolean",
      title: "Is Sys Admin",
      description:
        "Whether the authenticated user has the AIHubSysAdmin Keycloak realm role.",
    },
  },
  type: "object",
  required: ["is_sys_admin"],
  title: "WhoamiResponse",
} as const;
