// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  Composable,
  Options as Options2,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import {
  createTenantMetadataResponseTransformer,
  getAccessCapabilitiesResponseTransformer,
  getTenantResponseTransformer,
  listTenantsResponseTransformer,
  updateTenantMetadataResponseTransformer,
} from "./transformers.gen";
import type {
  AssignRoleData,
  AssignRoleError,
  AssignRoleResponse,
  CreateRoleData,
  CreateRoleError,
  CreateRoleResponse,
  CreateTenantMetadataData,
  CreateTenantMetadataError,
  CreateTenantMetadataResponse,
  DeleteRoleData,
  DeleteRoleError,
  DeleteRoleResponse2,
  DeleteTenantMetadataData,
  DeleteTenantMetadataError,
  DeleteTenantMetadataResponse,
  GetAccessCapabilitiesData,
  GetAccessCapabilitiesError,
  GetAccessCapabilitiesResponse,
  GetAccessPresetsData,
  GetAccessPresetsResponse,
  GetAuthProvidersData,
  GetAuthProvidersResponse,
  GetHealthData,
  GetHealthResponse,
  GetMyIdentityData,
  GetMyIdentityResponse,
  GetRoleData,
  GetRoleError,
  GetRoleResponse,
  GetRolesData,
  GetRolesResponse,
  GetTenantData,
  GetTenantError,
  GetTenantResponse,
  GetUserData,
  GetUserError,
  GetUserResponse,
  GetUsersData,
  GetUsersError,
  GetUsersResponse,
  ListTenantsData,
  ListTenantsResponse,
  ListUnconfiguredTenantsData,
  ListUnconfiguredTenantsResponse,
  RevokeRoleData,
  RevokeRoleError,
  RevokeRoleResponse,
  UpdateRoleData,
  UpdateRoleError,
  UpdateRoleResponse,
  UpdateTenantMetadataData,
  UpdateTenantMetadataError,
  UpdateTenantMetadataResponse,
} from "./types.gen";

export type Options<
  TComposable extends Composable = "$fetch",
  TData extends TDataShape = TDataShape,
  ResT = unknown,
  DefaultT = undefined,
> = Options2<TComposable, TData, ResT, DefaultT> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Health
 *
 * A simple liveness check endpoint that returns {"status": "ok"} if
 * the application is running and capable of handling requests.
 */
export const getHealth = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetHealthResponse = GetHealthResponse,
>(
  options: Options<TComposable, GetHealthData, GetHealthResponse, DefaultT>,
) =>
  (options.client ?? client).get<
    TComposable,
    GetHealthResponse | DefaultT,
    unknown,
    DefaultT
  >({ url: "/health/", ...options });

/**
 * List Tenants
 *
 * Lists all tenants: active (Keycloak + metadata) and orphaned (metadata only).
 */
export const listTenants = <
  TComposable extends Composable = "$fetch",
  DefaultT extends ListTenantsResponse = ListTenantsResponse,
>(
  options: Options<TComposable, ListTenantsData, ListTenantsResponse, DefaultT>,
) =>
  (options.client ?? client).get<
    TComposable,
    ListTenantsResponse | DefaultT,
    unknown,
    DefaultT
  >({
    responseTransformer: listTenantsResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/admin/tenants/",
    ...options,
  });

/**
 * Create Tenant Metadata
 *
 * Attaches metadata (name, description, access rules) to an existing Keycloak tenant group.
 */
export const createTenantMetadata = <
  TComposable extends Composable = "$fetch",
  DefaultT extends CreateTenantMetadataResponse = CreateTenantMetadataResponse,
>(
  options: Options<
    TComposable,
    CreateTenantMetadataData,
    CreateTenantMetadataResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).post<
    TComposable,
    CreateTenantMetadataResponse | DefaultT,
    CreateTenantMetadataError,
    DefaultT
  >({
    responseTransformer: createTenantMetadataResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/admin/tenants/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Unconfigured Tenants
 *
 * Lists Keycloak tenant group names that don't yet have metadata configured.
 */
export const listUnconfiguredTenants = <
  TComposable extends Composable = "$fetch",
  DefaultT extends ListUnconfiguredTenantsResponse =
    ListUnconfiguredTenantsResponse,
>(
  options: Options<
    TComposable,
    ListUnconfiguredTenantsData,
    ListUnconfiguredTenantsResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).get<
    TComposable,
    ListUnconfiguredTenantsResponse | DefaultT,
    unknown,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/admin/tenants/unconfigured",
    ...options,
  });

/**
 * Delete Tenant Metadata
 *
 * Removes the MongoDB metadata for the tenant. Allowed on both active and orphaned rows.
 *
 * The Keycloak group (if present) is not touched — manage it in the Keycloak admin console.
 * The last remaining tenant cannot be deleted (409); any tenant may be deleted as long as at
 * least one other tenant exists.
 */
export const deleteTenantMetadata = <
  TComposable extends Composable = "$fetch",
  DefaultT extends DeleteTenantMetadataResponse = DeleteTenantMetadataResponse,
>(
  options: Options<
    TComposable,
    DeleteTenantMetadataData,
    DeleteTenantMetadataResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).delete<
    TComposable,
    DeleteTenantMetadataResponse | DefaultT,
    DeleteTenantMetadataError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/admin/tenants/{tenant_id}",
    ...options,
  });

/**
 * Get Tenant
 *
 * Retrieves a single tenant by its ID.
 */
export const getTenant = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetTenantResponse = GetTenantResponse,
>(
  options: Options<TComposable, GetTenantData, GetTenantResponse, DefaultT>,
) =>
  (options.client ?? client).get<
    TComposable,
    GetTenantResponse | DefaultT,
    GetTenantError,
    DefaultT
  >({
    responseTransformer: getTenantResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/admin/tenants/{tenant_id}",
    ...options,
  });

/**
 * Update Tenant Metadata
 *
 * Updates a tenant's name, description, or access rules. Not allowed on orphaned tenants.
 */
export const updateTenantMetadata = <
  TComposable extends Composable = "$fetch",
  DefaultT extends UpdateTenantMetadataResponse = UpdateTenantMetadataResponse,
>(
  options: Options<
    TComposable,
    UpdateTenantMetadataData,
    UpdateTenantMetadataResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).patch<
    TComposable,
    UpdateTenantMetadataResponse | DefaultT,
    UpdateTenantMetadataError,
    DefaultT
  >({
    responseTransformer: updateTenantMetadataResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/admin/tenants/{tenant_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Identity
 *
 * Returns the authenticated user's identity (id, name, roles, sys-admin status, dashboard).
 *
 * Lightweight counterpart to ``get_my_account``: omits the access-rules matrix,
 * so this endpoint can be mounted on runners (e.g., sysadmin-api) that don't
 * wire NATS or i18n middleware. The ``{tenant_id}`` path segment is structural
 * (TenantScopedController prefix); the response does not depend on it, so any
 * value resolves — sysadmin-web's role-gate middleware passes ``"active"``.
 */
export const getMyIdentity = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetMyIdentityResponse = GetMyIdentityResponse,
>(
  options: Options<
    TComposable,
    GetMyIdentityData,
    GetMyIdentityResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).get<
    TComposable,
    GetMyIdentityResponse | DefaultT,
    unknown,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/my-account/identity",
    ...options,
  });

/**
 * Get User
 *
 * Retrieve user info by their OID. Shows access within the admin's current tenant context.
 */
export const getUser = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetUserResponse = GetUserResponse,
>(
  options: Options<TComposable, GetUserData, GetUserResponse, DefaultT>,
) =>
  (options.client ?? client).get<
    TComposable,
    GetUserResponse | DefaultT,
    GetUserError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/users/{user_id}",
    ...options,
  });

/**
 * Get Users
 *
 * Returns a paginated list of users within the requesting admin's tenant.
 */
export const getUsers = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetUsersResponse = GetUsersResponse,
>(
  options: Options<TComposable, GetUsersData, GetUsersResponse, DefaultT>,
) =>
  (options.client ?? client).get<
    TComposable,
    GetUsersResponse | DefaultT,
    GetUsersError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/users/",
    ...options,
  });

/**
 * Assign Role
 *
 * Assign a tenant role to the user. Returns the user's resulting role list within the tenant.
 */
export const assignRole = <
  TComposable extends Composable = "$fetch",
  DefaultT extends AssignRoleResponse = AssignRoleResponse,
>(
  options: Options<TComposable, AssignRoleData, AssignRoleResponse, DefaultT>,
) =>
  (options.client ?? client).post<
    TComposable,
    AssignRoleResponse | DefaultT,
    AssignRoleError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/users/{user_id}/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke Role
 *
 * Revoke a tenant role from the user. Returns the user's resulting role list within the tenant.
 */
export const revokeRole = <
  TComposable extends Composable = "$fetch",
  DefaultT extends RevokeRoleResponse = RevokeRoleResponse,
>(
  options: Options<TComposable, RevokeRoleData, RevokeRoleResponse, DefaultT>,
) =>
  (options.client ?? client).delete<
    TComposable,
    RevokeRoleResponse | DefaultT,
    RevokeRoleError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/users/{user_id}/roles/{role_name}",
    ...options,
  });

/**
 * Delete Role
 *
 * Permanently deletes a tenant-scoped role.
 */
export const deleteRole = <
  TComposable extends Composable = "$fetch",
  DefaultT extends DeleteRoleResponse2 = DeleteRoleResponse2,
>(
  options: Options<TComposable, DeleteRoleData, DeleteRoleResponse2, DefaultT>,
) =>
  (options.client ?? client).delete<
    TComposable,
    DeleteRoleResponse2 | DefaultT,
    DeleteRoleError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/roles/{role_id}",
    ...options,
  });

/**
 * Get Role
 *
 * Retrieves a single role by its unique ID.
 */
export const getRole = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetRoleResponse = GetRoleResponse,
>(
  options: Options<TComposable, GetRoleData, GetRoleResponse, DefaultT>,
) =>
  (options.client ?? client).get<
    TComposable,
    GetRoleResponse | DefaultT,
    GetRoleError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/roles/{role_id}",
    ...options,
  });

/**
 * Update Role
 *
 * Updates a tenant-scoped role's name, description, or access rules.
 */
export const updateRole = <
  TComposable extends Composable = "$fetch",
  DefaultT extends UpdateRoleResponse = UpdateRoleResponse,
>(
  options: Options<TComposable, UpdateRoleData, UpdateRoleResponse, DefaultT>,
) =>
  (options.client ?? client).patch<
    TComposable,
    UpdateRoleResponse | DefaultT,
    UpdateRoleError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/roles/{role_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Roles
 *
 * Retrieves all roles available to the current tenant (system + tenant-specific).
 */
export const getRoles = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetRolesResponse = GetRolesResponse,
>(
  options: Options<TComposable, GetRolesData, GetRolesResponse, DefaultT>,
) =>
  (options.client ?? client).get<
    TComposable,
    GetRolesResponse | DefaultT,
    unknown,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/roles/",
    ...options,
  });

/**
 * Create Role
 *
 * Creates a new tenant-scoped role with a name, description, and access rules.
 */
export const createRole = <
  TComposable extends Composable = "$fetch",
  DefaultT extends CreateRoleResponse = CreateRoleResponse,
>(
  options: Options<TComposable, CreateRoleData, CreateRoleResponse, DefaultT>,
) =>
  (options.client ?? client).post<
    TComposable,
    CreateRoleResponse | DefaultT,
    CreateRoleError,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/roles/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Evaluate Access Capabilities
 *
 * Returns the catalog of concrete capabilities (per service, agent and process), each with its exact access rule and whether the supplied draft rules grant it.
 */
export const getAccessCapabilities = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetAccessCapabilitiesResponse =
    GetAccessCapabilitiesResponse,
>(
  options: Options<
    TComposable,
    GetAccessCapabilitiesData,
    GetAccessCapabilitiesResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).post<
    TComposable,
    GetAccessCapabilitiesResponse | DefaultT,
    GetAccessCapabilitiesError,
    DefaultT
  >({
    responseTransformer: getAccessCapabilitiesResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/access/capabilities",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Access Presets
 *
 * Returns a curated, described library of common access rules for one-click authoring.
 */
export const getAccessPresets = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetAccessPresetsResponse = GetAccessPresetsResponse,
>(
  options: Options<
    TComposable,
    GetAccessPresetsData,
    GetAccessPresetsResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).get<
    TComposable,
    GetAccessPresetsResponse | DefaultT,
    unknown,
    DefaultT
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/{tenant_id}/access/presets",
    ...options,
  });

/**
 * Get Auth Providers
 */
export const getAuthProviders = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetAuthProvidersResponse = GetAuthProvidersResponse,
>(
  options: Options<
    TComposable,
    GetAuthProvidersData,
    GetAuthProvidersResponse,
    DefaultT
  >,
) =>
  (options.client ?? client).get<
    TComposable,
    GetAuthProvidersResponse | DefaultT,
    unknown,
    DefaultT
  >({ url: "/auth-providers/", ...options });
