// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Composable, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { createTenantMetadataResponseTransformer, getTenantResponseTransformer, listTenantsResponseTransformer, updateTenantMetadataResponseTransformer } from './transformers.gen';
import type { CreateTenantMetadataData, CreateTenantMetadataError, CreateTenantMetadataResponse, DeleteTenantMetadataData, DeleteTenantMetadataError, DeleteTenantMetadataResponse, GetTenantData, GetTenantError, GetTenantResponse, ListTenantsData, ListTenantsResponse, ListUnconfiguredTenantsData, ListUnconfiguredTenantsResponse, UpdateTenantMetadataData, UpdateTenantMetadataError, UpdateTenantMetadataResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Tenants
 *
 * Lists all tenants: active (Keycloak + metadata) and orphaned (metadata only).
 */
export const listTenants = <TComposable extends Composable = '$fetch', DefaultT extends ListTenantsResponse = ListTenantsResponse>(options: Options<TComposable, ListTenantsData, ListTenantsResponse, DefaultT>) => (options.client ?? client).get<TComposable, ListTenantsResponse | DefaultT, unknown, DefaultT>({
    responseTransformer: listTenantsResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/admin/tenants/',
    ...options
});

/**
 * Create Tenant Metadata
 *
 * Attaches metadata (name, description, access rules) to an existing Keycloak tenant group.
 */
export const createTenantMetadata = <TComposable extends Composable = '$fetch', DefaultT extends CreateTenantMetadataResponse = CreateTenantMetadataResponse>(options: Options<TComposable, CreateTenantMetadataData, CreateTenantMetadataResponse, DefaultT>) => (options.client ?? client).post<TComposable, CreateTenantMetadataResponse | DefaultT, CreateTenantMetadataError, DefaultT>({
    responseTransformer: createTenantMetadataResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/admin/tenants/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Unconfigured Tenants
 *
 * Lists Keycloak tenant group names that don't yet have metadata configured.
 */
export const listUnconfiguredTenants = <TComposable extends Composable = '$fetch', DefaultT extends ListUnconfiguredTenantsResponse = ListUnconfiguredTenantsResponse>(options: Options<TComposable, ListUnconfiguredTenantsData, ListUnconfiguredTenantsResponse, DefaultT>) => (options.client ?? client).get<TComposable, ListUnconfiguredTenantsResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/admin/tenants/unconfigured',
    ...options
});

/**
 * Delete Tenant Metadata
 *
 * Removes the MongoDB metadata for the tenant. Allowed on both active and orphaned rows.
 *
 * The Keycloak group (if present) is not touched — manage it in the Keycloak admin console.
 * The last remaining tenant cannot be deleted (409); any tenant may be deleted as long as at
 * least one other tenant exists.
 */
export const deleteTenantMetadata = <TComposable extends Composable = '$fetch', DefaultT extends DeleteTenantMetadataResponse = DeleteTenantMetadataResponse>(options: Options<TComposable, DeleteTenantMetadataData, DeleteTenantMetadataResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteTenantMetadataResponse | DefaultT, DeleteTenantMetadataError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/admin/tenants/{tenant_id}',
    ...options
});

/**
 * Get Tenant
 *
 * Retrieves a single tenant by its ID.
 */
export const getTenant = <TComposable extends Composable = '$fetch', DefaultT extends GetTenantResponse = GetTenantResponse>(options: Options<TComposable, GetTenantData, GetTenantResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetTenantResponse | DefaultT, GetTenantError, DefaultT>({
    responseTransformer: getTenantResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/admin/tenants/{tenant_id}',
    ...options
});

/**
 * Update Tenant Metadata
 *
 * Updates a tenant's name, description, or access rules. Not allowed on orphaned tenants.
 */
export const updateTenantMetadata = <TComposable extends Composable = '$fetch', DefaultT extends UpdateTenantMetadataResponse = UpdateTenantMetadataResponse>(options: Options<TComposable, UpdateTenantMetadataData, UpdateTenantMetadataResponse, DefaultT>) => (options.client ?? client).patch<TComposable, UpdateTenantMetadataResponse | DefaultT, UpdateTenantMetadataError, DefaultT>({
    responseTransformer: updateTenantMetadataResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/admin/tenants/{tenant_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
