// This file is auto-generated by @hey-api/openapi-ts

import type { CreateTenantMetadataResponse, GetTenantResponse, ListTenantsResponse, UpdateTenantMetadataResponse } from './types.gen';

const tenantResponseSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const listTenantsResponseTransformer = async (data: any): Promise<ListTenantsResponse> => {
    data = data.map((item: any) => tenantResponseSchemaResponseTransformer(item));
    return data;
};

export const createTenantMetadataResponseTransformer = async (data: any): Promise<CreateTenantMetadataResponse> => {
    data = tenantResponseSchemaResponseTransformer(data);
    return data;
};

export const getTenantResponseTransformer = async (data: any): Promise<GetTenantResponse> => {
    data = tenantResponseSchemaResponseTransformer(data);
    return data;
};

export const updateTenantMetadataResponseTransformer = async (data: any): Promise<UpdateTenantMetadataResponse> => {
    data = tenantResponseSchemaResponseTransformer(data);
    return data;
};
