// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}/api/v1` | (string & {});
};

/**
 * AgentHealthChecks
 *
 * Health check results for Agent service dependencies.
 */
export type AgentHealthChecks = {
  /**
   * Running
   *
   * Whether the agent runner is running.
   */
  running: boolean;
  /**
   * Nats
   *
   * NATS message broker connectivity.
   */
  nats: boolean;
  /**
   * Redis
   *
   * Redis/Valkey cache connectivity.
   */
  redis: boolean;
  /**
   * Milvus
   *
   * Milvus vector database connectivity.
   */
  milvus: boolean;
};

/**
 * ApiHealthChecks
 *
 * Health check results for API service dependencies.
 */
export type ApiHealthChecks = {
  /**
   * Nats
   *
   * NATS message broker connectivity.
   */
  nats: boolean;
  /**
   * Mongodb
   *
   * MongoDB database connectivity.
   */
  mongodb: boolean;
  /**
   * Redis
   *
   * Redis/Valkey cache connectivity.
   */
  redis: boolean;
  /**
   * Milvus
   *
   * Milvus vector database connectivity.
   */
  milvus: boolean;
  /**
   * S3
   *
   * S3/SeaweedFS object storage connectivity.
   */
  s3: boolean;
};

/**
 * CreateTenantMetadataRequest
 *
 * Request model for attaching metadata to an existing Keycloak tenant group.
 *
 * ``tenant_id`` is not user-chosen here — it must already exist as a Keycloak group
 * under ``/tenants/``. Use the ``/admin/tenants/unconfigured`` endpoint to list
 * configurable ids. A regex constraint is deliberately avoided because Keycloak
 * accepts group names this layer would otherwise reject (e.g. ``MyTenant``,
 * ``customer.acme``); the only checks that belong here are a minimum length (reject
 * empty payloads) and a maximum length matching Keycloak's group-name cap (DoS guard
 * against unbounded strings reaching Mongo).
 */
export type CreateTenantMetadataRequest = {
  /**
   * Tenant Id
   *
   * Keycloak tenant group name (must already exist under /tenants/).
   */
  tenant_id: string;
  /**
   * Name
   *
   * The unique display name of the tenant.
   */
  name: string;
  /**
   * Description
   *
   * A short description of the tenant.
   */
  description?: string;
  /**
   * Access Rules
   *
   * Access rules granted to this tenant.
   */
  access_rules?: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Standard health check response.
 */
export type HealthResponse = {
  /**
   * Status
   *
   * The health status of the application.
   */
  status: string;
  /**
   * Code
   *
   * HTTP status code.
   */
  code: number;
  /**
   * Checks
   *
   * Individual health check results.
   */
  checks?: ApiHealthChecks | AgentHealthChecks | ProcessHealthChecks | null;
};

/**
 * ProcessHealthChecks
 *
 * Health check results for Process service dependencies.
 */
export type ProcessHealthChecks = {
  /**
   * Running
   *
   * Whether the process runner is running.
   */
  running: boolean;
  /**
   * Nats
   *
   * NATS message broker connectivity.
   */
  nats: boolean;
  /**
   * Redis
   *
   * Redis/Valkey cache connectivity.
   */
  redis: boolean;
};

/**
 * TenantResponse
 *
 * Response model for a tenant, as seen by sysadmins.
 */
export type TenantResponse = {
  /**
   * Id
   *
   * Unique tenant identifier (matches the Keycloak group name).
   */
  id: string;
  /**
   * Name
   *
   * Tenant display name.
   */
  name: string;
  /**
   * Description
   *
   * Tenant description.
   */
  description: string;
  /**
   * Access Rules
   *
   * Access rules granted to this tenant.
   */
  access_rules: Array<string>;
  /**
   * Whether the tenant also exists in Keycloak (active) or not (orphaned).
   */
  state: TenantState;
  /**
   * Created At
   *
   * Tenant creation timestamp.
   */
  created_at: Date;
  /**
   * Updated At
   *
   * Tenant last update timestamp.
   */
  updated_at: Date;
};

/**
 * TenantState
 *
 * Visibility state of a tenant for the sysadmin view.
 *
 * - ACTIVE: exists both in Keycloak (as a group) and in MongoDB (as metadata).
 * - ORPHANED: exists only in MongoDB; the Keycloak group is missing. Users cannot
 * reach this tenant. Shown to sysadmins read-only with a delete action only.
 *
 * Unconfigured tenants (Keycloak group only, no metadata) deliberately do not
 * appear here: they carry no MongoDB fields (name/description/access_rules) to
 * wrap in a ``TenantResponse``, so they are served separately as ``list[str]``
 * by ``/admin/tenants/unconfigured``. Promoting one to Active via
 * ``create_tenant_metadata`` is what introduces the metadata row that makes a
 * ``TenantState`` value meaningful.
 */
export const TenantState = { ACTIVE: "active", ORPHANED: "orphaned" } as const;

/**
 * TenantState
 *
 * Visibility state of a tenant for the sysadmin view.
 *
 * - ACTIVE: exists both in Keycloak (as a group) and in MongoDB (as metadata).
 * - ORPHANED: exists only in MongoDB; the Keycloak group is missing. Users cannot
 * reach this tenant. Shown to sysadmins read-only with a delete action only.
 *
 * Unconfigured tenants (Keycloak group only, no metadata) deliberately do not
 * appear here: they carry no MongoDB fields (name/description/access_rules) to
 * wrap in a ``TenantResponse``, so they are served separately as ``list[str]``
 * by ``/admin/tenants/unconfigured``. Promoting one to Active via
 * ``create_tenant_metadata`` is what introduces the metadata row that makes a
 * ``TenantState`` value meaningful.
 */
export type TenantState = (typeof TenantState)[keyof typeof TenantState];

/**
 * UpdateTenantMetadataRequest
 *
 * Request model for updating a tenant. All fields are optional.
 *
 * Name and description constraints mirror ``CreateTenantMetadataRequest`` — an update
 * must not be able to slip a value past a constraint that create enforced.
 */
export type UpdateTenantMetadataRequest = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Access Rules
   *
   * Access rules granted to this tenant.
   */
  access_rules?: Array<string> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * WhoamiResponse
 */
export type WhoamiResponse = {
  /**
   * Is Sys Admin
   *
   * Whether the authenticated user has the AIHubSysAdmin Keycloak realm role.
   */
  is_sys_admin: boolean;
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/";
};

export type GetHealthResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetWhoamiData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/whoami/";
};

export type GetWhoamiResponses = {
  /**
   * Successful Response
   */
  200: WhoamiResponse;
};

export type GetWhoamiResponse = GetWhoamiResponses[keyof GetWhoamiResponses];

export type ListTenantsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/tenants/";
};

export type ListTenantsResponses = {
  /**
   * Response List Tenants Admin Tenants  Get
   *
   * Successful Response
   */
  200: Array<TenantResponse>;
};

export type ListTenantsResponse =
  ListTenantsResponses[keyof ListTenantsResponses];

export type CreateTenantMetadataData = {
  body: CreateTenantMetadataRequest;
  path?: never;
  query?: never;
  url: "/admin/tenants/";
};

export type CreateTenantMetadataErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTenantMetadataError =
  CreateTenantMetadataErrors[keyof CreateTenantMetadataErrors];

export type CreateTenantMetadataResponses = {
  /**
   * Successful Response
   */
  201: TenantResponse;
};

export type CreateTenantMetadataResponse =
  CreateTenantMetadataResponses[keyof CreateTenantMetadataResponses];

export type ListUnconfiguredTenantsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/tenants/unconfigured";
};

export type ListUnconfiguredTenantsResponses = {
  /**
   * Response List Unconfigured Tenants Admin Tenants Unconfigured Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ListUnconfiguredTenantsResponse =
  ListUnconfiguredTenantsResponses[keyof ListUnconfiguredTenantsResponses];

export type DeleteTenantMetadataData = {
  body?: never;
  path: {
    /**
     * Tenant Id
     */
    tenant_id: string;
  };
  query?: never;
  url: "/admin/tenants/{tenant_id}";
};

export type DeleteTenantMetadataErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTenantMetadataError =
  DeleteTenantMetadataErrors[keyof DeleteTenantMetadataErrors];

export type DeleteTenantMetadataResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTenantMetadataResponse =
  DeleteTenantMetadataResponses[keyof DeleteTenantMetadataResponses];

export type GetTenantData = {
  body?: never;
  path: {
    /**
     * Tenant Id
     */
    tenant_id: string;
  };
  query?: never;
  url: "/admin/tenants/{tenant_id}";
};

export type GetTenantErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTenantError = GetTenantErrors[keyof GetTenantErrors];

export type GetTenantResponses = {
  /**
   * Successful Response
   */
  200: TenantResponse;
};

export type GetTenantResponse = GetTenantResponses[keyof GetTenantResponses];

export type UpdateTenantMetadataData = {
  body: UpdateTenantMetadataRequest;
  path: {
    /**
     * Tenant Id
     */
    tenant_id: string;
  };
  query?: never;
  url: "/admin/tenants/{tenant_id}";
};

export type UpdateTenantMetadataErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTenantMetadataError =
  UpdateTenantMetadataErrors[keyof UpdateTenantMetadataErrors];

export type UpdateTenantMetadataResponses = {
  /**
   * Successful Response
   */
  200: TenantResponse;
};

export type UpdateTenantMetadataResponse =
  UpdateTenantMetadataResponses[keyof UpdateTenantMetadataResponses];
