from pydantic import BaseModel, Field


class MessageResponse(BaseModel):
    """
    Represents a message in the response from the chat completion API, following OpenAI's message structure.
    """

    role: str = Field(
        ...,
        description="The role of the message author. In responses, this is typically 'assistant'",
        example="assistant",
    )
    content: str = Field(
        ...,
        description="The content of the message generated by the model",
        example="Hello! I'm here to help. How can I assist you today?",
    )
