from pathlib import PurePosixPath

from swiss_ai_hub.core.generative_ai.document.parsers.markdown_structural_node_parser import find_markdown_headers

_FENCE_MARKERS = ("```", "~~~")


class DocumentTitleDeriver:
    """Derives a document title: email subject, else the first markdown heading, else the filename stem.

    Nothing derived a title before this. Every `document_title` in the platform is the last path segment of the
    source URI, which for `2f8c-invoice-final-v2.pdf` is not what a person would call the document.
    """

    @staticmethod
    def derive(content: str, filename: str, subject: str | None = None, content_is_markdown: bool = True) -> str:
        """`subject` wins when present because a mail states its own title; a heading is only an inference.

        `content_is_markdown` is what keeps the heading step honest for verbatim text. A `#` opens a comment in
        YAML, TOML, INI and most config formats, so a `prod-config.yml` starting `# Generated by tooling` would
        otherwise be titled after its own do-not-edit banner — worse than the filename it replaced.
        """
        if subject and subject.strip():
            return subject.strip()

        if content_is_markdown:
            heading = DocumentTitleDeriver._first_heading(content)
            if heading:
                return heading

        return PurePosixPath(filename).stem or filename

    @staticmethod
    def _first_heading(content: str) -> str:
        """The first markdown heading of any level, ignoring fenced blocks.

        Not the first `#`: MinerU labels a scanned document's title by its visual prominence, which is not always
        level 1, so a page whose largest text is rendered as `##` would otherwise fall through to the filename.
        Fenced blocks are skipped because `find_markdown_headers` scans lines without tracking them, and a shell
        comment inside an example is not the document's title.
        """
        headings = {header.line_number: header.header_text.strip() for header in find_markdown_headers(content)}
        if not headings:
            return ""

        fenced = False
        for line_number, line in enumerate(content.splitlines()):
            if line.lstrip().startswith(_FENCE_MARKERS):
                fenced = not fenced
                continue
            if not fenced and headings.get(line_number):
                return headings[line_number]
        return ""
