{{- if .Values.phoenix.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aihub.fullname" (dict "component" "phoenix" "Values" .Values "Release" .Release) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix
spec:
  replicas: {{ .Values.phoenix.replicas }}
  selector:
    matchLabels:
      {{- include "aihub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: phoenix
  template:
    metadata:
      labels:
        {{- include "aihub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: phoenix
    spec:
      securityContext:
        {{- include "aihub.podSecurityContext" . | nindent 8 }}
      containers:
      - name: phoenix
        image: {{ .Values.phoenix.image.repository }}:{{ .Values.phoenix.image.tag }}
        imagePullPolicy: {{ .Values.phoenix.image.pullPolicy }}
        securityContext:
          {{- include "aihub.securityContext" . | nindent 10 }}
        env:
        {{- include "aihub.commonEnv" . | nindent 8 }}
        - name: PHOENIX_SQL_DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ include "aihub.fullname" (dict "component" "postgres" "Values" .Values "Release" .Release) }}:5432/phoenix"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" .  }}-env
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ include "aihub.fullname" .  }}-env
              key: POSTGRES_PASSWORD
        - name: PHOENIX_ENABLE_AUTH
          value: "False"
        - name: VERSION
          value: ""
        ports:
        - containerPort: 6006
          name: phoenix
        resources:
          {{- toYaml .Values.phoenix.resources | nindent 10 }}
      volumes:
{{- end }}
