{{- if .Values.phoenix.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aihub.fullname" (dict "component" "phoenix" "Values" .Values "Release" .Release) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix
spec:
  type: {{ .Values.phoenix.service.type }}
  ports:
  - port: {{ .Values.phoenix.service.port }}
    targetPort: 6006
    protocol: TCP
    name: phoenix
  selector:
    {{- include "aihub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix
{{- end }}
