// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateDatasetResponse,
  CreateTokenEndpointResponse,
  GetAccessCapabilitiesResponse,
  GetAgentEventTimeseriesResponse,
  GetDatasetResponse,
  GetDatasetsResponse,
  GetNotificationsResponse,
  ListTokensEndpointResponse,
  UpdateDatasetResponse,
  UpdateNotificationResponse,
  UpdateNotificationsBulkResponse,
} from "./types.gen";

const eventBucketSchemaResponseTransformer = (data: any) => {
  data.start_time = new Date(data.start_time);
  data.end_time = new Date(data.end_time);
  return data;
};

const eventTimeseriesSchemaResponseTransformer = (data: any) => {
  data.start_time = new Date(data.start_time);
  data.end_time = new Date(data.end_time);
  data.buckets = data.buckets.map((item: any) =>
    eventBucketSchemaResponseTransformer(item),
  );
  return data;
};

export const getAgentEventTimeseriesResponseTransformer = async (
  data: any,
): Promise<GetAgentEventTimeseriesResponse> => {
  data = eventTimeseriesSchemaResponseTransformer(data);
  return data;
};

const tokenResponseSchemaResponseTransformer = (data: any) => {
  data.expiry_date = new Date(data.expiry_date);
  return data;
};

export const listTokensEndpointResponseTransformer = async (
  data: any,
): Promise<ListTokensEndpointResponse> => {
  data = data.map((item: any) => tokenResponseSchemaResponseTransformer(item));
  return data;
};

const createTokenResponseSchemaResponseTransformer = (data: any) => {
  data.expiry_date = new Date(data.expiry_date);
  return data;
};

export const createTokenEndpointResponseTransformer = async (
  data: any,
): Promise<CreateTokenEndpointResponse> => {
  data = createTokenResponseSchemaResponseTransformer(data);
  return data;
};

const capabilityGroupSchemaResponseTransformer = (data: any) => {
  if (data.groups) {
    data.groups = data.groups.map((item: any) =>
      capabilityGroupSchemaResponseTransformer(item),
    );
  }
  return data;
};

const accessCapabilitiesResponseSchemaResponseTransformer = (data: any) => {
  data.groups = data.groups.map((item: any) =>
    capabilityGroupSchemaResponseTransformer(item),
  );
  return data;
};

export const getAccessCapabilitiesResponseTransformer = async (
  data: any,
): Promise<GetAccessCapabilitiesResponse> => {
  data = accessCapabilitiesResponseSchemaResponseTransformer(data);
  return data;
};

const minimalDatasetSchemaResponseTransformer = (data: any) => {
  if (data.created_at) {
    data.created_at = new Date(data.created_at);
  }
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const getDatasetsResponseTransformer = async (
  data: any,
): Promise<GetDatasetsResponse> => {
  data = data.map((item: any) => minimalDatasetSchemaResponseTransformer(item));
  return data;
};

const datasetSchemaResponseTransformer = (data: any) => {
  if (data.created_at) {
    data.created_at = new Date(data.created_at);
  }
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const createDatasetResponseTransformer = async (
  data: any,
): Promise<CreateDatasetResponse> => {
  data = datasetSchemaResponseTransformer(data);
  return data;
};

export const getDatasetResponseTransformer = async (
  data: any,
): Promise<GetDatasetResponse> => {
  data = datasetSchemaResponseTransformer(data);
  return data;
};

export const updateDatasetResponseTransformer = async (
  data: any,
): Promise<UpdateDatasetResponse> => {
  data = datasetSchemaResponseTransformer(data);
  return data;
};

const notificationDtoSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

const paginatedNotificationsResponseSchemaResponseTransformer = (data: any) => {
  data.notifications = data.notifications.map((item: any) =>
    notificationDtoSchemaResponseTransformer(item),
  );
  return data;
};

export const getNotificationsResponseTransformer = async (
  data: any,
): Promise<GetNotificationsResponse> => {
  data = paginatedNotificationsResponseSchemaResponseTransformer(data);
  return data;
};

export const updateNotificationsBulkResponseTransformer = async (
  data: any,
): Promise<UpdateNotificationsBulkResponse> => {
  data = data.map((item: any) =>
    notificationDtoSchemaResponseTransformer(item),
  );
  return data;
};

export const updateNotificationResponseTransformer = async (
  data: any,
): Promise<UpdateNotificationResponse> => {
  data = notificationDtoSchemaResponseTransformer(data);
  return data;
};
