from swiss_ai_hub.core.infrastructure import DocumentIngestionPipelineSettings, enable_logging

from swiss_ai_hub.pipeline.util.document_ingestion_definitions_util import document_ingestion_pipeline_definitions

enable_logging()

defs = document_ingestion_pipeline_definitions(settings=DocumentIngestionPipelineSettings())
