[tool.poetry]
name = "aihub_iac"
version = "v0.245.5"
description = "iac core"
authors = [
    "Joel Barmettler <joel.barmettler@bbv.ch>",
    "Marius Högger <marius.hoegger@bbv.ch>",
    "Michèle Fundneider <michele.fundneider@bbv.ch>",
    "Thomas Mannhart <thomas.mannhart@bbv.ch>",
    "Noah Hermann <noah.hermann@bbv.ch>",
]
license = "Proprietary"

[tool.poetry.dependencies]
python = ">=3.13, <3.14"
pydantic = "^2.10.3"
pulumi-azure-native = "^3.5.0"
pydantic-settings = "^2.9.1"
pulumi-command = "^1.0.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^0.24.0"
ruff = "^0.8.1"
mypy = "^1.13.0"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = 'py313'

[tool.ruff.lint]
select = ["E", "F", "UP", "I"]

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

