{{- if .Values.etcd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aihub.fullname" (dict "component" "etcd" "context" .) }}
  labels:
    {{- include "aihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
spec:
  type: {{ .Values.etcd.service.type }}
  ports:
  - port: {{ .Values.etcd.service.port }}
    targetPort: 2379
    protocol: TCP
    name: etcd
  selector:
    {{- include "aihub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
{{- end }}
