#!/bin/sh
# This file is auto-generated from a Jinja2 template.
# DO NOT EDIT THIS FILE DIRECTLY.
#
# To make changes, edit deployment/templates/configs/init_etcd.sh.j2
set -e

echo "Waiting for etcd to be reachable..."
until etcdctl endpoint health >/dev/null 2>&1; do
  # If this fails because auth is ALREADY enabled, we can skip the wait
  if etcdctl --user="root:${ETCD_ROOT_PASSWORD}" endpoint health >/dev/null 2>&1; then
     echo "Auth already active and etcd is healthy."
     exit 0
  fi
  sleep 2
done

# Check if auth is already enabled by attempting an unauthenticated call
if etcdctl user list >/dev/null 2>&1; then
    echo "Authentication not enabled. Setting up..."
    # Create root role (may already exist)
    etcdctl role add root 2>/dev/null || true
    # Create root user
    etcdctl user add "root:${ETCD_ROOT_PASSWORD}" --interactive=false
    # Grant root role to root user
    etcdctl user grant-role root root
    # Enable authentication
    etcdctl auth enable
    echo "Authentication enabled successfully."
else
    echo "Authentication appears to be already enabled."
fi
