import json
import logging
from typing import Optional, List

from flatdict import FlatterDict
from llama_index.core.base.llms.types import ChatResponseGen, ChatMessage
from llama_index.core.callbacks import TokenCountingHandler
from llama_index.core.llms import LLM

from opentelemetry import trace

from lib_core.generative_ai.llms.costs.LLMCostTracker import LLMCostTracker
from lib_core.generative_ai.llms.models.LLMConfig import LLMConfig
from lib_core.nats.events import DisplayEvent, ChunkEvent, ThoughtEvent, LLMEvent
from lib_core.nats.events.cost.LLMCostEvent import LLMCostEvent
from lib_core.nats.events.semantic import Message
from lib_core.nats.publishers.JSPublisher import JSPublisher
from lib_core.nats.topic_managers.agents.AgentThreadTopicManager import AgentThreadTopicManager

logger = logging.getLogger(__name__)


class EventDisplayer:

    def __init__(self, publisher: JSPublisher, topic_manager: AgentThreadTopicManager):
        self.publisher = publisher
        self.topic_manager = topic_manager

    async def display_event(self, event: DisplayEvent, content: Optional[str] = None):
        subject = self.topic_manager.get_subject_for_display_event_in_thread(event.__class__.__name__, event.event_id)
        attributes = FlatterDict(event.model_dump(), delimiter=".").as_dict()

        current_span = trace.get_current_span()
        current_span.add_event(
            name=f"{event.__class__.__name__}: {content or json.dumps(attributes)}",
            attributes=attributes
        )

        await self.publisher.publish_event(event, subject)

    async def display_chunk(self, content: str):
        event = ChunkEvent(content=content)
        await self.display_event(event, content=content)

    async def display_thought(self, thought: str):
        event = ThoughtEvent(content=thought)
        await self.display_event(event, content=thought)

    async def display_llm_costs(self, model_name: str, cost_tracker: LLMCostTracker):
        llm_cost_event = LLMCostEvent.from_llm_costs(
            llm_name=model_name,
            costs=cost_tracker.get_total_costs(),
        )
        await self.display_event(llm_cost_event)

    async def display_llm_stream(self, llm_config: LLMConfig, llm: LLM, messages: List[ChatMessage]) -> LLMEvent:
        aggregate = ""
        buffer = ""
        max_buffer_length = 500

        # Iterate over the chunks generated by the LLM
        for chunk in llm.stream_chat(messages):
            content = chunk.delta
            aggregate += content
            buffer += content

            # Process as long as there's at least one newline in the buffer
            while "\n" in buffer:
                # Split at the first newline
                section, buffer = buffer.split("\n", 1)
                # Display the section + newline as a separate chunk
                await self.display_chunk(section + "\n")

            # If no newline but buffer is getting large, flush to avoid delay
            if len(buffer) > max_buffer_length:
                await self.display_chunk(buffer)
                buffer = ""

        # After the loop, if there's any leftover in the buffer, flush it
        if buffer:
            await self.display_chunk(buffer)

        handlers = llm.callback_manager.handlers
        token_count_handler = next((h for h in handlers if isinstance(h, TokenCountingHandler)), None)
        if token_count_handler:
            token_count_prompt = token_count_handler.prompt_llm_token_count
            token_count_completion = token_count_handler.completion_llm_token_count
        else:
            token_count_prompt = 0
            token_count_completion = 0

        return LLMEvent(
            input_messages=[Message(role=msg.role, content=msg.content) for msg in messages],
            output_messages=[Message(role="assistant", content=aggregate)],
            invocation_parameters=llm_config.model_dump(),
            chat_model_name = llm_config.name,
            provider = llm_config.__class__.__name__,
            token_count_prompt = token_count_prompt,
            token_count_completion = token_count_completion,
            token_count_total = token_count_prompt + token_count_completion,
        )
