name: Analyze & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

permissions:
  contents: read
  security-events: write

jobs:
  sonarcloud-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    permissions:
      contents: read
      security-events: write

    strategy:
      matrix:
        folder: [ aihub_agent, aihub_api, aihub_lib, aihub_pipeline, aihub_web ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ matrix.folder }}
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
