name: Analyze & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - initiative/*
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test-modules:
    name: Test Modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [aihub_lib, aihub_api, aihub_agent, aihub_pipeline]

    environment:
      name: Development

    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      pull-requests: write

    outputs:
      test_report_passed: ${{ steps.test_report.outputs.passed }}
      test_report_failed: ${{ steps.test_report.outputs.failed }}
      test_report_skipped: ${{ steps.test_report.outputs.skipped }}
      test_report_time: ${{ steps.test_report.outputs.time }}
      test_report_url_html: ${{ steps.test_report.outputs.url_html }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      # Start Docker services for aihub_agent only
      - name: Start Docker services
        if: matrix.module == 'aihub_agent'
        run: |
          docker-compose -f playground/docker-compose.yml up -d
        working-directory: aihub_agent

      # Wait for services to initialize
      - name: Wait for Docker services
        if: matrix.module == 'aihub_agent'
        run: |
          until nc -z localhost 4222; do
            echo "Waiting for NATS service to be ready..."
            sleep 3
          done
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB service to be ready..."
            sleep 3
          done

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: ${{ matrix.module }}/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('${{ matrix.module }}/poetry.lock') }}

      - name: Validate poetry.lock
        run: poetry lock --no-update
        working-directory: ${{ matrix.module }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
        working-directory: ${{ matrix.module }}

      - name: Install project
        run: poetry install --no-interaction
        working-directory: ${{ matrix.module }}

      - name: Run tests with coverage and generate report
        run: |
          make test-cov || echo "TEST_FAIL=true" >> $GITHUB_ENV
        working-directory: ${{ matrix.module }}
        env:
          ORIGINAL_AZURE_SUBSCRIPTION_NAME: ${{ vars.AZURE_SUBSCRIPTION_NAME }}
          ORIGINAL_ENVIRONMENT: ${{ vars.ENV_SHORT }}
          ORIGINAL_APP_NAME: ${{ vars.APP_NAME }}
          ORIGINAL_REGION_SHORT: ${{ vars.REGION_SHORT }}

      # Stop Docker services after tests
      - name: Stop Docker services
        if: matrix.module == 'aihub_agent'
        run: |
          docker-compose -f playground/docker-compose.yml down
        working-directory: aihub_agent

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-coverage-report
          path: ${{ matrix.module }}/coverage.xml

      - name: Upload pytest report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-pytest-report
          path: ${{ matrix.module }}/pytest.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ matrix.module }}/pytest.xml

      - name: Check if tests failed
        if: env.TEST_FAIL == 'true'
        run: |
          echo "Tests have failed!"
          exit 1

  pytest-coverage-comment:
    name: Pytest Coverage Comment
    needs: test-modules
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      pull-requests: write
      checks: write

    strategy:
      matrix:
        module: [ aihub_lib, aihub_api, aihub_agent, aihub_pipeline ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download pytest reports
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.module }}-pytest-report
          path: ${{ matrix.module }}

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.module }}-coverage-report
          path: ${{ matrix.module }}

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ${{ matrix.module }}/pytest.xml
          pytest-xml-coverage-path: ${{ matrix.module }}/coverage.xml
          coverage-path-prefix: ${{ matrix.module }}
          title: Tests for ${{ matrix.module }}
          default-branch: dev
          report-only-changed-files: true

  sonarcloud-agent:
    name: SonarCloud Agents Core
    runs-on: ubuntu-latest
    if: always()

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: aihub_agent
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

  sonarcloud-api:
    name: SonarCloud API Core
    runs-on: ubuntu-latest
    if: always()

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: aihub_api
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

  sonarcloud-lib:
    name: SonarCloud Lib Core
    runs-on: ubuntu-latest
    if: always()

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: aihub_lib
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

  sonarcloud-pipeline:
    name: SonarCloud Pipelines Core
    runs-on: ubuntu-latest
    if: always()

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: aihub_pipeline
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

  sonarcloud-web:
    name: SonarCloud Web Core
    runs-on: ubuntu-latest
    if: always()

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: aihub_web
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
