name: Semantic PR

on:
  pull_request:
    branches: [ main, initiative/* ]
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  lint-pr-title:
    name: Lint PR Title
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    permissions:
      checks: write
      contents: read
      pull-requests: read

    steps:
      - name: Semantic Pull Request
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            aihub
            agent-custom
            agent-xp
            avatar
            chat-xp
            chat-backend
            debt
            dagster
            confidence
            deploy
            ui
            guards
            rag
            local
            tracing
            workflows
            micro
          types: |
            fix
            feat
            doc
            test
            chore

          requireScope: true
          subjectPattern: ^([A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.

  lint-branch-name:
    name: Lint Branch Name
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    permissions:
      checks: write
      contents: read
      pull-requests: read
    steps:
      - name: Lint branch name
        uses: lekterable/branchlint-action@2.1.0
        with:
          errorMessage: 'Invalid branch name. Please follow the pattern'
          allowed: |
            main
            initiative/agent-custom
            initiative/agent-xp
            initiative/avatar
            initiative/chat-xp
            initiative/chat-backend
            initiative/debt
            initiative/dagster
            initiative/confidence
            initiative/deploy
            initiative/ui
            initiative/guards
            initiative/rag
            initiative/local
            initiative/tracing
            initiative/workflows
            initiative/micro
            initiative/bots
            /^(quickfix|hotfix|agent-custom|agent-xp|avatar|chat-xp|chat-backend|debt|dagster|confidence|deploy|ui|guards|rag|local|tracing|workflows|micro|bots)\/([a-z-0-9])+$/
